In [1]:
%load_ext autoreload
%autoreload 2
%xmode Plain

Exception reporting mode: Plain

In [2]:
import pandas as pd
import plotly
import plotly.express as px 
import dtale
import numpy as np
import random
from bazaraki import utils
from tqdm import tqdm
import swifter
from pathlib import Path
import datacompy
from datetime import datetime, date
from parse import parse
from glob import glob

/var/folders/gv/96s0_n4j4xl87r8p93wpnf0r0000gp/T/ipykernel_60203/3232598961.py:11: UserWarning:

Python 3.12 and above currently is not supported by Spark and Ray. Please note that some functionality will not work and currently is not supported.

/var/folders/gv/96s0_n4j4xl87r8p93wpnf0r0000gp/T/ipykernel_60203/3232598961.py:11: UserWarning:

SparkPandasCompare currently only supports Numpy < 2.Please note that the SparkPandasCompare functionality will not work and currently is not supported.

In [3]:
pd.set_option('display.max_rows', 50)  # Disable row limit
pd.set_option('display.max_columns', 40)  # Disable column limit
pd.set_option('display.width', 20)  # Disable line width limit
pd.set_option('display.max_colwidth', 100)  # Disable column width limit
# Set the display precision to 2 decimal places  
pd.set_option('display.precision', 2)  
  
# Or set the float format to always show 2 decimal places  
pd.set_option('display.float_format', '{:.2f}'.format)

In [4]:
pd.options.plotting.backend = "plotly"
plotly.io.renderers.default = "notebook_connected"

In [5]:
df = utils.read_dfs("output/*.parquet")
# df = utils.read_dfs("output/2025-04-*.parquet")

Reading output/2024-12-12 18:34:25 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2024-12-14 11:44:22 real-estate-to-rent_real-estate-for-sale.parquet
Total: 35559 valid: 34669 read: 34669 new: 745 deleted: 890 undeleted: 0
Reading output/2024-12-15 18:00:14 real-estate-to-rent_real-estate-for-sale.parquet
Total: 35734 valid: 34398 read: 34398 new: 175 deleted: 490 undeleted: 44
Reading output/2024-12-16 23:13:52 real-estate-to-rent_real-estate-for-sale.parquet
Total: 36281 valid: 34510 read: 34510 new: 547 deleted: 648 undeleted: 213
Reading output/2024-12-17 21:31:02 real-estate-to-rent_real-estate-for-sale.parquet
Total: 37085 valid: 34681 read: 34681 new: 804 deleted: 817 undeleted: 184
Reading output/2024-12-18 23:01:10 real-estate-to-rent_real-estate-for-sale.parquet
Total: 37577 valid: 34809 read: 34809 new: 492 deleted: 468 undeleted: 104
Reading output/2024-12-19 22:09:26 real-estate-to-rent_real-estate-for-sale.parquet
Total: 38047 valid: 33723 read: 33723 new: 470 deleted: 1666 undeleted: 110
Reading output/2024-12-22 21:49:27 real-estate-to-rent_real-estate-for-sale.parquet
Total: 39161 valid: 33255 read: 33255 new: 1114 deleted: 1851 undeleted: 269
Reading output/2024-12-23 19:08:45 real-estate-to-rent_real-estate-for-sale.parquet
Total: 39512 valid: 33936 read: 33936 new: 351 deleted: 443 undeleted: 773
Reading output/2024-12-27 17:28:17 real-estate-to-rent_real-estate-for-sale.parquet
Total: 39938 valid: 32909 read: 32909 new: 426 deleted: 1633 undeleted: 180
Reading output/2024-12-29 13:00:58 real-estate-to-rent_real-estate-for-sale.parquet
Total: 40131 valid: 32452 read: 32452 new: 193 deleted: 783 undeleted: 133
Reading output/2025-01-02 12:05:37 real-estate-to-rent_real-estate-for-sale.parquet
Total: 40786 valid: 32633 read: 32633 new: 655 deleted: 1426 undeleted: 952
Reading output/2025-01-09 16:40:56 real-estate-to-rent_real-estate-for-sale.parquet
Total: 42992 valid: 33259 read: 33259 new: 2206 deleted: 2876 undeleted: 1296
Reading output/2025-01-11 16:28:55 real-estate-to-rent_real-estate-for-sale.parquet
Total: 43667 valid: 33450 read: 33450 new: 675 deleted: 910 undeleted: 426
Reading output/2025-01-13 19:44:12 real-estate-to-rent_real-estate-for-sale.parquet
Total: 44692 valid: 32624 read: 32624 new: 1025 deleted: 2309 undeleted: 458
Reading output/2025-01-14 17:35:36 real-estate-to-rent_real-estate-for-sale.parquet
Total: 45301 valid: 33324 read: 33324 new: 609 deleted: 511 undeleted: 602
Reading output/2025-01-16 22:17:14 real-estate-to-rent_real-estate-for-sale.parquet
Total: 46878 valid: 34023 read: 34023 new: 1577 deleted: 1285 undeleted: 407
Reading output/2025-01-20 18:35:48 real-estate-to-rent_real-estate-for-sale.parquet
Total: 48068 valid: 33904 read: 33904 new: 1190 deleted: 1825 undeleted: 516
Reading output/2025-01-29 12:26:50 real-estate-to-rent_real-estate-for-sale.parquet
Total: 52581 valid: 36128 read: 36128 new: 4513 deleted: 3302 undeleted: 1013
Reading output/2025-01-30 20:47:55 real-estate-to-rent_real-estate-for-sale.parquet
Total: 53294 valid: 36344 read: 36344 new: 713 deleted: 747 undeleted: 250
Reading output/2025-02-04 21:11:22 real-estate-to-rent_real-estate-for-sale.parquet
Total: 55192 valid: 36326 read: 36326 new: 1898 deleted: 2529 undeleted: 613
Reading output/2025-02-05 18:32:44 real-estate-to-rent_real-estate-for-sale.parquet
Total: 55698 valid: 36184 read: 36184 new: 506 deleted: 788 undeleted: 140
Reading output/2025-02-10 14:44:23 real-estate-to-rent_real-estate-for-sale.parquet
Total: 57381 valid: 36042 read: 36042 new: 1683 deleted: 2387 undeleted: 562
Reading output/2025-02-22 13:10:31 real-estate-to-rent_real-estate-for-sale.parquet
Total: 62687 valid: 37449 read: 37449 new: 5306 deleted: 5699 undeleted: 1800
Reading output/2025-03-22 11:44:38 real-estate-to-rent_real-estate-for-sale.parquet
Total: 75232 valid: 38077 read: 38077 new: 12545 deleted: 13216 undeleted: 1299
Reading output/2025-04-05 11:05:29 real-estate-to-rent_real-estate-for-sale.parquet
Total: 81786 valid: 37955 read: 37955 new: 6554 deleted: 10515 undeleted: 3839
Reading output/2025-04-06 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (37953 rows vs 81786 known in its rubrics)
Reading output/2025-04-07 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (37898 rows vs 81786 known in its rubrics)
Reading output/2025-04-08 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (37981 rows vs 81786 known in its rubrics)
Reading output/2025-04-09 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38143 rows vs 81786 known in its rubrics)
Reading output/2025-04-10 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38198 rows vs 81786 known in its rubrics)
Reading output/2025-04-11 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38103 rows vs 81786 known in its rubrics)
Reading output/2025-04-12 00:00:01 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38197 rows vs 81786 known in its rubrics)
Reading output/2025-04-13 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38032 rows vs 81786 known in its rubrics)
Reading output/2025-04-14 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38018 rows vs 81786 known in its rubrics)
Reading output/2025-04-15 00:00:01 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38263 rows vs 81786 known in its rubrics)
Reading output/2025-04-16 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38310 rows vs 81786 known in its rubrics)
Reading output/2025-04-17 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38362 rows vs 81786 known in its rubrics)
Reading output/2025-04-18 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38221 rows vs 81786 known in its rubrics)
Reading output/2025-04-19 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38245 rows vs 81786 known in its rubrics)
Reading output/2025-04-20 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38076 rows vs 81786 known in its rubrics)
Reading output/2025-04-21 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (37978 rows vs 81786 known in its rubrics)
Reading output/2025-04-22 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (37932 rows vs 81786 known in its rubrics)
Reading output/2025-04-23 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (37903 rows vs 81786 known in its rubrics)
Reading output/2025-04-24 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (37961 rows vs 81786 known in its rubrics)
Reading output/2025-04-25 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38009 rows vs 81786 known in its rubrics)
Reading output/2025-04-28 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (37758 rows vs 81786 known in its rubrics)
Reading output/2025-05-01 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38151 rows vs 81786 known in its rubrics)
Reading output/2025-05-04 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38072 rows vs 81786 known in its rubrics)
Reading output/2025-05-07 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (37982 rows vs 81786 known in its rubrics)
Reading output/2025-05-10 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38042 rows vs 81786 known in its rubrics)
Reading output/2025-05-13 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (37990 rows vs 81786 known in its rubrics)
Reading output/2025-05-16 00:00:02 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38156 rows vs 81786 known in its rubrics)
Reading output/2025-05-19 00:00:01 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38018 rows vs 81786 known in its rubrics)
Reading output/2025-05-22 00:00:02 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38352 rows vs 81786 known in its rubrics)
Reading output/2025-05-25 00:00:03 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38270 rows vs 81786 known in its rubrics)
Reading output/2025-05-28 00:00:03 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38240 rows vs 81786 known in its rubrics)
Reading output/2025-05-31 00:00:02 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38501 rows vs 81786 known in its rubrics)
Reading output/2025-06-01 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38481 rows vs 81786 known in its rubrics)
Reading output/2025-06-04 00:00:03 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38582 rows vs 81786 known in its rubrics)
Reading output/2025-08-13 10:28:42 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38115 rows vs 81786 known in its rubrics)
Reading output/2025-08-16 00:00:01 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (37866 rows vs 81786 known in its rubrics)
Reading output/2025-08-19 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (37805 rows vs 81786 known in its rubrics)
Reading output/2025-08-22 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (37856 rows vs 81786 known in its rubrics)
Reading output/2025-08-25 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (37648 rows vs 81786 known in its rubrics)
Reading output/2025-08-28 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (37975 rows vs 81786 known in its rubrics)
Reading output/2025-08-31 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38060 rows vs 81786 known in its rubrics)
Reading output/2025-09-01 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38002 rows vs 81786 known in its rubrics)
Reading output/2025-09-04 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38225 rows vs 81786 known in its rubrics)
Reading output/2025-09-07 00:00:02 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (36866 rows vs 81786 known in its rubrics)
Reading output/2025-09-10 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (37352 rows vs 81786 known in its rubrics)
Reading output/2025-09-13 00:00:02 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38731 rows vs 81786 known in its rubrics)
Reading output/2025-09-16 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38682 rows vs 81786 known in its rubrics)
Reading output/2025-09-19 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39070 rows vs 81786 known in its rubrics)
Reading output/2025-09-22 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38854 rows vs 81786 known in its rubrics)
Reading output/2025-09-25 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39086 rows vs 81786 known in its rubrics)
Reading output/2025-09-28 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38914 rows vs 81786 known in its rubrics)
Reading output/2025-10-01 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38881 rows vs 81786 known in its rubrics)
Reading output/2025-10-04 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38682 rows vs 81786 known in its rubrics)
Reading output/2025-10-07 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38648 rows vs 81786 known in its rubrics)
Reading output/2025-10-10 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38876 rows vs 81786 known in its rubrics)
Reading output/2025-10-14 07:20:23 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38929 rows vs 81786 known in its rubrics)
Reading output/2025-10-16 00:01:44 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39066 rows vs 81786 known in its rubrics)
Reading output/2025-10-19 07:29:40 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38820 rows vs 81786 known in its rubrics)
Reading output/2025-10-22 00:01:58 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39052 rows vs 81786 known in its rubrics)
Reading output/2025-10-25 00:01:51 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39138 rows vs 81786 known in its rubrics)
Reading output/2025-10-28 00:01:41 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39041 rows vs 81786 known in its rubrics)
Reading output/2025-10-31 00:01:50 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39011 rows vs 81786 known in its rubrics)
Reading output/2025-11-01 00:02:19 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39038 rows vs 81786 known in its rubrics)
Reading output/2025-11-01 11:23:53 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38952 rows vs 81786 known in its rubrics)
Reading output/2025-11-04 00:01:41 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38964 rows vs 81786 known in its rubrics)
Reading output/2025-11-07 00:01:37 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39053 rows vs 81786 known in its rubrics)
Reading output/2025-11-10 00:01:32 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38858 rows vs 81786 known in its rubrics)
Reading output/2025-11-13 00:01:28 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39215 rows vs 81786 known in its rubrics)
Reading output/2025-11-19 00:01:35 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39293 rows vs 81786 known in its rubrics)
Reading output/2025-11-22 00:01:24 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39431 rows vs 81786 known in its rubrics)
Reading output/2025-11-25 00:04:21 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39374 rows vs 81786 known in its rubrics)
Reading output/2025-11-28 00:01:35 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39432 rows vs 81786 known in its rubrics)
Reading output/2025-12-01 00:01:33 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39295 rows vs 81786 known in its rubrics)
Reading output/2025-12-04 00:01:37 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39437 rows vs 81786 known in its rubrics)
Reading output/2025-12-07 00:01:32 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39302 rows vs 81786 known in its rubrics)
Reading output/2025-12-10 00:01:36 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39304 rows vs 81786 known in its rubrics)
Reading output/2025-12-13 00:01:24 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39536 rows vs 81786 known in its rubrics)
Reading output/2025-12-16 00:01:40 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39438 rows vs 81786 known in its rubrics)
Reading output/2025-12-19 00:01:32 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39414 rows vs 81786 known in its rubrics)
Reading output/2025-12-22 00:01:27 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39186 rows vs 81786 known in its rubrics)
Reading output/2025-12-25 00:01:24 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39034 rows vs 81786 known in its rubrics)
Reading output/2026-01-04 19:37:32 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38406 rows vs 81786 known in its rubrics)
Reading output/2026-01-07 00:37:07 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38555 rows vs 81786 known in its rubrics)
Reading output/2026-01-10 00:37:39 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38804 rows vs 81786 known in its rubrics)
Reading output/2026-01-13 00:34:06 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38859 rows vs 81786 known in its rubrics)
Reading output/2026-01-16 00:38:34 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39178 rows vs 81786 known in its rubrics)
Reading output/2026-01-19 00:40:48 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39092 rows vs 81786 known in its rubrics)
Reading output/2026-01-22 00:39:15 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39331 rows vs 81786 known in its rubrics)
Reading output/2026-01-25 00:42:35 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39205 rows vs 81786 known in its rubrics)
Reading output/2026-01-28 00:38:23 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39369 rows vs 81786 known in its rubrics)
Reading output/2026-01-31 00:42:01 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39271 rows vs 81786 known in its rubrics)
Reading output/2026-02-01 00:52:39 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39236 rows vs 81786 known in its rubrics)
Reading output/2026-02-04 00:42:38 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39471 rows vs 81786 known in its rubrics)
Reading output/2026-02-07 00:42:59 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39540 rows vs 81786 known in its rubrics)
Reading output/2026-02-10 00:52:30 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39191 rows vs 81786 known in its rubrics)
Reading output/2026-02-13 00:48:55 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39125 rows vs 81786 known in its rubrics)
Reading output/2026-02-16 00:46:53 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38931 rows vs 81786 known in its rubrics)
Reading output/2026-02-19 00:47:02 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39047 rows vs 81786 known in its rubrics)
Reading output/2026-02-22 00:46:51 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38829 rows vs 81786 known in its rubrics)
Reading output/2026-02-25 00:48:45 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38832 rows vs 81786 known in its rubrics)
Reading output/2026-02-28 00:40:26 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39051 rows vs 81786 known in its rubrics)
Reading output/2026-03-01 00:51:44 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38939 rows vs 81786 known in its rubrics)
Reading output/2026-03-04 00:44:19 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (38999 rows vs 81786 known in its rubrics)
Reading output/2026-03-07 00:43:02 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39145 rows vs 81786 known in its rubrics)
Reading output/2026-03-16 00:47:52 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39163 rows vs 81786 known in its rubrics)
Reading output/2026-03-19 00:43:50 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39316 rows vs 81786 known in its rubrics)
Reading output/2026-03-22 00:44:44 real-estate-to-rent_real-estate-for-sale.parquet
Skipping partial run (39319 rows vs 81786 known in its rubrics)

In [6]:
df.iloc[0].T

url                                                 https://www.bazaraki.com/adv/5415213_4-bedroom-detached-house-to-rent/
title                                                                                     4-bedroom detached house to rent
price                                                                                                              1650.00
original_price                                                                                                         NaN
price_per_sqm                                                                                                          NaN
location                                                                                               Larnaca, Dromolaxia
posted                                                                                                     Yesterday 20:57
reference_number                                                                                                       NaN
views                                                                                                                  472
lat                                                                                                                  34.87
lng                                                                                                                  33.59
sold                                                                                                                 False
cat0                                                                                            Cyprus real estate to rent
cat1                                                                                                        Houses to rent
Property area                                                                                                       218.00
Pets                                                                                                           Not allowed
Type                                                                                                        Detached house
Parking                                                                                                          Uncovered
Plot area                                                                                                           542.00
Furnishing                                                                                                 Fully Furnished
Included                                                                                                   Garden, Balcony
Online viewing                                                                                                         Yes
Air conditioning                                                                                           Full, all rooms
Energy Efficiency                                                                                                      N/A
Bedrooms                                                                                                                 4
Bathrooms                                                                                                                2
images                 [https://cdn1.bazaraki.com/media/cache1/af/7a/af7a55295335956b16be66e00547ef40.webp, https://cdn...
description            This spacious four-bedroom house is located in a quiet neighborhood and is perfect for families ...
Floor                                                                                                                 None
Postal code                                                                                                            NaN
Construction year                                                                                                     None
Reference number                                                                                                      None
Condition                                                                                                             None
Square meter price                                                                                                    None
Minimum stay                                                                                                          None
Land type                                                                                                             None
Plot Type                                                                                                             None
Parcel number                                                                                                         None
Planning zone                                                                                                         None
Registration number                                                                                                    NaN
Share                                                                                                                 None
Density                                                                                                               None
Coverage                                                                                                              None
Registration block                                                                                                     NaN
Area                                                                                                                   NaN
Pick a point                                                                                                          None
posted_dt                                                                                              2024-12-11T20:57:00
delete_date                                                                                                     2025-01-20
Property Type                                                                                                          NaN
Name: 5415213, dtype: object

In [7]:
df.cat1.unique()

array(['Houses to rent', 'Apartments, flats to rent', 'Houses for sale',
       'Apartments, flats for sale', 'Commercial property', 'Short term',
       'Plots of land', 'Rooms, flatmates', 'Prefabricated houses',
       'Residential buildings', 'Other'], dtype=object)

In [8]:
df1 = df.query("cat1 == 'Apartments, flats to rent' and not delete_date.isna()").copy()
df1.posted_dt = pd.to_datetime(df1.posted_dt)
df1.delete_date = pd.to_datetime(df1.delete_date)
df1

,url,title,price,original_price,price_per_sqm,location,posted,reference_number,views,lat,lng,sold,cat0,cat1,Property area,Pets,Type,Parking,Plot area,Furnishing,...,Postal code,Construction year,Reference number,Condition,Square meter price,Minimum stay,Land type,Plot Type,Parcel number,Planning zone,Registration number,Share,Density,Coverage,Registration block,Area,Pick a point,posted_dt,delete_date,Property Type
ad_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
5508233,https://www.bazaraki.com/adv/5508233_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,1150.00,NaN,NaN,"Paphos, Chlorakas",Yesterday 21:02,NaN,385,34.79,32.42,False,Cyprus real estate to rent,"Apartments, flats to rent",100.00,Allowed,Apartment,Uncovered,NaN,Fully Furnished,...,8220.00,2008,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,None,2024-12-11 21:02:00,2025-01-11,NaN
5395481,https://www.bazaraki.com/adv/5395481_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,1100.00,NaN,NaN,"Larnaca, Livadia Larnakas",07.12.2024 11:07,NaN,26,34.95,33.64,False,Cyprus real estate to rent,"Apartments, flats to rent",90.00,Not allowed,Apartment,Covered,NaN,Fully Furnished,...,7060.00,2015,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,None,2024-12-07 11:07:00,2025-01-20,NaN
5562261,https://www.bazaraki.com/adv/5562261_1-bedroom-apartment-to-rent/,1-bedroom apartment to rent,720.00,NaN,NaN,"Nicosia, Nicosia - Ag. Antonios",07.12.2024 12:34,NaN,45,35.17,33.37,False,Cyprus real estate to rent,"Apartments, flats to rent",60.00,Not allowed,Apartment,Covered,NaN,Unfurnished,...,NaN,2015,rentonline-107,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,None,2024-12-07 12:34:00,2025-02-10,NaN
5525766,https://www.bazaraki.com/adv/5525766_1-bedroom-apartment-to-rent/,1-bedroom apartment to rent,1200.00,NaN,NaN,"Limassol, Polemidia Kato",08.12.2024 19:03,NaN,37,NaN,NaN,False,Cyprus real estate to rent,"Apartments, flats to rent",65.00,Allowed,Apartment,Covered,NaN,Fully Furnished,...,NaN,2011,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,None,2024-12-08 19:03:00,2024-12-22,NaN
5534586,https://www.bazaraki.com/adv/5534586_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,1500.00,NaN,NaN,"Limassol, Limassol - Petrou Kai Pavlou",08.12.2024 19:03,NaN,13,NaN,NaN,False,Cyprus real estate to rent,"Apartments, flats to rent",85.00,Not allowed,Apartment,Uncovered,NaN,Fully Furnished,...,NaN,2012,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,None,2024-12-08 19:03:00,2025-01-14,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5737674,https://www.bazaraki.com/adv/5737674_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,800.00,NaN,NaN,"Nicosia, Aglantzia",13:08,NaN,3,35.15,33.40,False,Cyprus real estate to rent,"Apartments, flats to rent",85.00,Not allowed,Apartment,Uncovered,NaN,Fully Furnished,...,2114.00,2010,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2025-04-05 13:08:00,2026-08-26,NaN
5737696,https://www.bazaraki.com/adv/5737696_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,900.00,NaN,NaN,"Larnaca, Drosia",13:19,NaN,2,34.92,33.62,False,Cyprus real estate to rent,"Apartments, flats to rent",80.00,Not allowed,Apartment,Covered,NaN,Fully Furnished,...,NaN,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2025-04-05 13:19:00,2026-08-26,NaN
5737713,https://www.bazaraki.com/adv/5737713_studio-apartment-to-rent/,1-bedroom apartment to rent,1000.00,NaN,NaN,"Limassol, Limassol - Zakaki",13:47,NaN,4,34.66,33.01,False,Cyprus real estate to rent,"Apartments, flats to rent",50.00,Allowed,Apartment,Uncovered,NaN,Fully Furnished,...,NaN,2024,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2025-04-05 13:47:00,2026-08-26,NaN
5737720,https://www.bazaraki.com/adv/5737720_2-bedroom-penthouse-to-rent/,2-bedroom penthouse to rent,1900.00,NaN,NaN,"Limassol, Polemidia Kato",13:36,NaN,3,34.68,33.00,False,Cyprus real estate to rent,"Apartments, flats to rent",95.00,None,Penthouse,Covered,NaN,Fully Furnished,...,NaN,2024,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2025-04-05 13:36:00,2026-08-26,NaN
5737731,https://www.bazaraki.com/adv/5737731_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,1500.00,NaN,NaN,"Limassol, Polemidia Kato",13:42,NaN,1,34.68,33.00,False,Cyprus real estate to rent,"Apartments, flats to rent",85.00,None,Apartment,Covered,NaN,Fully Furnished,...,NaN,2023,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2025-04-05 13:42:00,2026-08-26,NaN

In [9]:
df1["age_days"] = (df1["delete_date"] - df1["posted_dt"]).dt.days
df1

,url,title,price,original_price,price_per_sqm,location,posted,reference_number,views,lat,lng,sold,cat0,cat1,Property area,Pets,Type,Parking,Plot area,Furnishing,...,Construction year,Reference number,Condition,Square meter price,Minimum stay,Land type,Plot Type,Parcel number,Planning zone,Registration number,Share,Density,Coverage,Registration block,Area,Pick a point,posted_dt,delete_date,Property Type,age_days
ad_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
5508233,https://www.bazaraki.com/adv/5508233_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,1150.00,NaN,NaN,"Paphos, Chlorakas",Yesterday 21:02,NaN,385,34.79,32.42,False,Cyprus real estate to rent,"Apartments, flats to rent",100.00,Allowed,Apartment,Uncovered,NaN,Fully Furnished,...,2008,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,None,2024-12-11 21:02:00,2025-01-11,NaN,30
5395481,https://www.bazaraki.com/adv/5395481_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,1100.00,NaN,NaN,"Larnaca, Livadia Larnakas",07.12.2024 11:07,NaN,26,34.95,33.64,False,Cyprus real estate to rent,"Apartments, flats to rent",90.00,Not allowed,Apartment,Covered,NaN,Fully Furnished,...,2015,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,None,2024-12-07 11:07:00,2025-01-20,NaN,43
5562261,https://www.bazaraki.com/adv/5562261_1-bedroom-apartment-to-rent/,1-bedroom apartment to rent,720.00,NaN,NaN,"Nicosia, Nicosia - Ag. Antonios",07.12.2024 12:34,NaN,45,35.17,33.37,False,Cyprus real estate to rent,"Apartments, flats to rent",60.00,Not allowed,Apartment,Covered,NaN,Unfurnished,...,2015,rentonline-107,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,None,2024-12-07 12:34:00,2025-02-10,NaN,64
5525766,https://www.bazaraki.com/adv/5525766_1-bedroom-apartment-to-rent/,1-bedroom apartment to rent,1200.00,NaN,NaN,"Limassol, Polemidia Kato",08.12.2024 19:03,NaN,37,NaN,NaN,False,Cyprus real estate to rent,"Apartments, flats to rent",65.00,Allowed,Apartment,Covered,NaN,Fully Furnished,...,2011,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,None,2024-12-08 19:03:00,2024-12-22,NaN,13
5534586,https://www.bazaraki.com/adv/5534586_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,1500.00,NaN,NaN,"Limassol, Limassol - Petrou Kai Pavlou",08.12.2024 19:03,NaN,13,NaN,NaN,False,Cyprus real estate to rent,"Apartments, flats to rent",85.00,Not allowed,Apartment,Uncovered,NaN,Fully Furnished,...,2012,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,None,2024-12-08 19:03:00,2025-01-14,NaN,36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5737674,https://www.bazaraki.com/adv/5737674_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,800.00,NaN,NaN,"Nicosia, Aglantzia",13:08,NaN,3,35.15,33.40,False,Cyprus real estate to rent,"Apartments, flats to rent",85.00,Not allowed,Apartment,Uncovered,NaN,Fully Furnished,...,2010,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2025-04-05 13:08:00,2026-08-26,NaN,507
5737696,https://www.bazaraki.com/adv/5737696_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,900.00,NaN,NaN,"Larnaca, Drosia",13:19,NaN,2,34.92,33.62,False,Cyprus real estate to rent,"Apartments, flats to rent",80.00,Not allowed,Apartment,Covered,NaN,Fully Furnished,...,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2025-04-05 13:19:00,2026-08-26,NaN,507
5737713,https://www.bazaraki.com/adv/5737713_studio-apartment-to-rent/,1-bedroom apartment to rent,1000.00,NaN,NaN,"Limassol, Limassol - Zakaki",13:47,NaN,4,34.66,33.01,False,Cyprus real estate to rent,"Apartments, flats to rent",50.00,Allowed,Apartment,Uncovered,NaN,Fully Furnished,...,2024,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2025-04-05 13:47:00,2026-08-26,NaN,507
5737720,https://www.bazaraki.com/adv/5737720_2-bedroom-penthouse-to-rent/,2-bedroom penthouse to rent,1900.00,NaN,NaN,"Limassol, Polemidia Kato",13:36,NaN,3,34.68,33.00,False,Cyprus real estate to rent,"Apartments, flats to rent",95.00,None,Penthouse,Covered,NaN,Fully Furnished,...,2024,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2025-04-05 13:36:00,2026-08-26,NaN,507
5737731,https://www.bazaraki.com/adv/5737731_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,1500.00,NaN,NaN,"Limassol, Polemidia Kato",13:42,NaN,1,34.68,33.00,False,Cyprus real estate to rent,"Apartments, flats to rent",85.00,None,Apartment,Covered,NaN,Fully Furnished,...,2023,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2025-04-05 13:42:00,2026-08-26,NaN,507

In [10]:
df2 = utils.add_city_disctrict_cols(df1)
df2.iloc[0].T

url               https://www.bazaraki.com/adv/5508233_2-bedroom-apartment-to-rent/
title                                                   2-bedroom apartment to rent
price                                                                       1150.00
original_price                                                                  NaN
price_per_sqm                                                                   NaN
                                                ...
delete_date                                                     2025-01-11 00:00:00
Property Type                                                                   NaN
age_days                                                                         30
city                                                                         Paphos
district                                                                  Chlorakas
Name: 5508233, Length: 52, dtype: object

In [11]:
df1.groupby(["city", "Bedrooms"]).agg(
    mean_age_days=("age_days", "mean"),
    median_age_days=("age_days", "median"),
    count=("age_days", "count")
).reset_index().sort_values("median_age_days", ascending=True).round(2).query("count > 10 and Bedrooms in ['1', '2', '3', 'Studio']")

,city,Bedrooms,mean_age_days,median_age_days,count
0,Famagusta,1,92.80,30.50,44
17,Limassol,Studio,131.36,30.50,216
2,Famagusta,3,123.46,32.00,13
23,Nicosia,Studio,141.22,32.00,120
4,Famagusta,Studio,69.77,32.00,13
29,Paphos,Studio,140.15,32.50,66
11,Limassol,1,139.29,33.00,1310
24,Paphos,1,130.48,34.00,315
18,Nicosia,1,149.22,35.00,1330
1,Famagusta,2,137.59,37.50,100
25,Paphos,2,170.49,40.00,765
26,Paphos,3,178.62,41.50,212
12,Limassol,2,183.03,42.00,3575
5,Larnaca,1,183.98,42.00,393
10,Larnaca,Studio,198.40,44.00,55
19,Nicosia,2,186.35,46.00,2213
6,Larnaca,2,209.08,51.00,1403
13,Limassol,3,201.79,52.00,2042
20,Nicosia,3,208.61,58.00,1147
7,Larnaca,3,232.36,70.00,373

In [12]:
# check examples
df1.query("city == 'Larnaca' and Bedrooms == 'Studio'")

,url,title,price,original_price,price_per_sqm,location,posted,reference_number,views,lat,lng,sold,cat0,cat1,Property area,Pets,Type,Parking,Plot area,Furnishing,...,Condition,Square meter price,Minimum stay,Land type,Plot Type,Parcel number,Planning zone,Registration number,Share,Density,Coverage,Registration block,Area,Pick a point,posted_dt,delete_date,Property Type,age_days,city,district
ad_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
3753553,https://www.bazaraki.com/adv/3753553_studio-on-the-sea-in-dekelia/,Studio apartment to rent,580.00,NaN,NaN,"Larnaca, Oroklini",09.12.2024 06:40,NaN,52,NaN,NaN,False,Cyprus real estate to rent,"Apartments, flats to rent",30.00,Not allowed,Apartment,Uncovered,NaN,Fully Furnished,...,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,None,2024-12-09 06:40:00,2026-08-26,NaN,624,Larnaca,Oroklini
4852027,https://www.bazaraki.com/adv/4852027_studio-apartment-to-rent/,Studio apartment to rent,450.00,500.00,NaN,"Larnaca, Perivolia Larnakas",07.12.2024 13:30,NaN,14537,NaN,NaN,False,Cyprus real estate to rent,"Apartments, flats to rent",0.00,Not allowed,Apartment,Covered,NaN,Fully Furnished,...,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,None,2024-12-07 13:30:00,2025-02-22,NaN,76,Larnaca,Perivolia Larnakas
5416646,https://www.bazaraki.com/adv/5416646_studio-apartment-to-rent/,Studio apartment to rent,600.00,NaN,NaN,"Larnaca, Larnaka - Finikoudes",14.11.2024 00:01,NaN,558,NaN,NaN,False,Cyprus real estate to rent,"Apartments, flats to rent",25.00,Allowed,Apartment,No,NaN,Fully Furnished,...,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,None,2024-11-14 00:01:00,2026-08-26,NaN,649,Larnaca,Larnaka - Finikoudes
5349458,https://www.bazaraki.com/adv/5349458_studio-apartment-to-rent/,Studio apartment to rent,580.00,NaN,NaN,"Larnaca, Larnaka - Makenzy",18.11.2024 14:50,NaN,2313,34.90,33.63,False,Cyprus real estate to rent,"Apartments, flats to rent",24.00,Not allowed,Apartment,Uncovered,NaN,Fully Furnished,...,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,None,2024-11-18 14:50:00,2026-08-26,NaN,645,Larnaca,Larnaka - Makenzy
5534674,https://www.bazaraki.com/adv/5534674_studio-apartment-to-rent/,Studio apartment to rent,950.00,NaN,NaN,"Larnaca, Larnaka - Finikoudes",18.11.2024 15:12,NaN,184,34.91,33.63,False,Cyprus real estate to rent,"Apartments, flats to rent",80.00,Not allowed,Apartment,Covered,NaN,Fully Furnished,...,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,None,2024-11-18 15:12:00,2025-02-04,NaN,77,Larnaca,Larnaka - Finikoudes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5723547,https://www.bazaraki.com/adv/5723547_studio-apartment-to-rent/,Studio apartment to rent,550.00,NaN,NaN,"Larnaca, Larnaka - Harbor",28.03.2025 11:28,NaN,231,34.92,33.64,False,Cyprus real estate to rent,"Apartments, flats to rent",45.00,Not allowed,Apartment,Covered,NaN,Fully Furnished,...,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2025-03-28 11:28:00,2026-08-26,NaN,515,Larnaca,Larnaka - Harbor
5723891,https://www.bazaraki.com/adv/5723891_studio-apartment-to-rent/,Studio apartment to rent,1100.00,NaN,NaN,"Larnaca, Larnaka - Makenzy",28.03.2025 14:42,NaN,74,34.90,33.64,False,Cyprus real estate to rent,"Apartments, flats to rent",33.00,None,Apartment,No,NaN,Fully Furnished,...,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2025-03-28 14:42:00,2026-08-26,NaN,515,Larnaca,Larnaka - Makenzy
5727562,https://www.bazaraki.com/adv/5727562_studio-apartment-to-rent/,Studio apartment to rent,1000.00,NaN,NaN,"Larnaca, Larnaka - Makenzy",31.03.2025 13:37,NaN,41,NaN,NaN,False,Cyprus real estate to rent,"Apartments, flats to rent",35.00,None,Apartment,Uncovered,NaN,Fully Furnished,...,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2025-03-31 13:37:00,2026-08-26,NaN,512,Larnaca,Larnaka - Makenzy
5729377,https://www.bazaraki.com/adv/5729377_studio-apartment-to-rent/,Studio apartment to rent,530.00,NaN,NaN,"Larnaca, Larnaka - Finikoudes",01.04.2025 12:05,NaN,282,34.92,33.64,True,Cyprus real estate to rent,"Apartments, flats to rent",38.00,Not allowed,Apartment,No,NaN,Fully Furnished,...,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2025-04-01 12:05:00,2026-08-26,NaN,511,Larnaca,Larnaka - Finikoudes
5730419,https://www.bazaraki.com/adv/5730419_studio-apartment-to-rent/,Studio apartment to rent,850.00,NaN,NaN,"Larnaca, Drosia",01.04.2025 23:49,NaN,41,34.92,33.62,False,Cyprus real estate to rent,"Apartments, flats to rent",45.00,Not allowed,Apartment,Covered,NaN,Fully Furnished,...,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2025-04-01 23:49:00,2026-08-26,NaN,511,Larnaca,Drosia