In [2]:
%load_ext autoreload
%autoreload 2
%xmode Plain

Exception reporting mode: Plain

In [3]:
import pandas as pd
import plotly
import plotly.express as px 
import dtale
import numpy as np
import random
from bazaraki import utils
from tqdm import tqdm
import swifter
from pathlib import Path
import datacompy
from datetime import datetime, date
from parse import parse
from glob import glob

/var/folders/gv/96s0_n4j4xl87r8p93wpnf0r0000gp/T/ipykernel_33804/3232598961.py:11: UserWarning:

Python 3.12 and above currently is not supported by Spark and Ray. Please note that some functionality will not work and currently is not supported.

/var/folders/gv/96s0_n4j4xl87r8p93wpnf0r0000gp/T/ipykernel_33804/3232598961.py:11: UserWarning:

SparkPandasCompare currently only supports Numpy < 2.Please note that the SparkPandasCompare functionality will not work and currently is not supported.

In [4]:
# dont limit pandas columns output
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', 300)

In [5]:
pd.set_option('display.max_rows', 50)  # Disable row limit
pd.set_option('display.max_columns', 40)  # Disable column limit
pd.set_option('display.width', 20)  # Disable line width limit
pd.set_option('display.max_colwidth', 100)  # Disable column width limit
# Set the display precision to 2 decimal places  
pd.set_option('display.precision', 2)  
  
# Or set the float format to always show 2 decimal places  
pd.set_option('display.float_format', '{:.2f}'.format)

In [6]:
pd.options.plotting.backend = "plotly"
plotly.io.renderers.default = "notebook_connected"

In [6]:
df = utils.read_dfs("output/*.parquet")

Reading output/2024-12-12 18:34:25 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2024-12-14 11:44:22 real-estate-to-rent_real-estate-for-sale.parquet
Total: 35559 valid: 34669 read: 34669 new: 745 deleted: 890 undeleted: 0
Reading output/2024-12-15 18:00:14 real-estate-to-rent_real-estate-for-sale.parquet
Total: 35734 valid: 34398 read: 34398 new: 175 deleted: 490 undeleted: 44
Reading output/2024-12-16 23:13:52 real-estate-to-rent_real-estate-for-sale.parquet
Total: 36281 valid: 34510 read: 34510 new: 547 deleted: 648 undeleted: 213
Reading output/2024-12-17 21:31:02 real-estate-to-rent_real-estate-for-sale.parquet
Total: 37085 valid: 34681 read: 34681 new: 804 deleted: 817 undeleted: 184
Reading output/2024-12-18 23:01:10 real-estate-to-rent_real-estate-for-sale.parquet
Total: 37577 valid: 34809 read: 34809 new: 492 deleted: 468 undeleted: 104
Reading output/2024-12-19 22:09:26 real-estate-to-rent_real-estate-for-sale.parquet
Total: 38047 valid: 33723 read: 33723 new: 470 deleted: 1666 undeleted: 110
Reading output/2024-12-22 21:49:27 real-estate-to-rent_real-estate-for-sale.parquet
Total: 39161 valid: 33255 read: 33255 new: 1114 deleted: 1851 undeleted: 269
Reading output/2024-12-23 19:08:45 real-estate-to-rent_real-estate-for-sale.parquet
Total: 39512 valid: 33936 read: 33936 new: 351 deleted: 443 undeleted: 773
Reading output/2024-12-27 17:28:17 real-estate-to-rent_real-estate-for-sale.parquet
Total: 39938 valid: 32909 read: 32909 new: 426 deleted: 1633 undeleted: 180
Reading output/2024-12-29 13:00:58 real-estate-to-rent_real-estate-for-sale.parquet
Total: 40131 valid: 32452 read: 32452 new: 193 deleted: 783 undeleted: 133
Reading output/2025-01-02 12:05:37 real-estate-to-rent_real-estate-for-sale.parquet
Total: 40786 valid: 32633 read: 32633 new: 655 deleted: 1426 undeleted: 952
Reading output/2025-01-09 16:40:56 real-estate-to-rent_real-estate-for-sale.parquet
Total: 42992 valid: 33259 read: 33259 new: 2206 deleted: 2876 undeleted: 1296
Reading output/2025-01-11 16:28:55 real-estate-to-rent_real-estate-for-sale.parquet
Total: 43667 valid: 33450 read: 33450 new: 675 deleted: 910 undeleted: 426
Reading output/2025-01-13 19:44:12 real-estate-to-rent_real-estate-for-sale.parquet
Total: 44692 valid: 32624 read: 32624 new: 1025 deleted: 2309 undeleted: 458
Reading output/2025-01-14 17:35:36 real-estate-to-rent_real-estate-for-sale.parquet
Total: 45301 valid: 33324 read: 33324 new: 609 deleted: 511 undeleted: 602
Reading output/2025-01-16 22:17:14 real-estate-to-rent_real-estate-for-sale.parquet
Total: 46878 valid: 34023 read: 34023 new: 1577 deleted: 1285 undeleted: 407
Reading output/2025-01-20 18:35:48 real-estate-to-rent_real-estate-for-sale.parquet
Total: 48068 valid: 33904 read: 33904 new: 1190 deleted: 1825 undeleted: 516
Reading output/2025-01-29 12:26:50 real-estate-to-rent_real-estate-for-sale.parquet
Total: 52581 valid: 36128 read: 36128 new: 4513 deleted: 3302 undeleted: 1013
Reading output/2025-01-30 20:47:55 real-estate-to-rent_real-estate-for-sale.parquet
Total: 53294 valid: 36344 read: 36344 new: 713 deleted: 747 undeleted: 250
Reading output/2025-02-04 21:11:22 real-estate-to-rent_real-estate-for-sale.parquet
Total: 55192 valid: 36326 read: 36326 new: 1898 deleted: 2529 undeleted: 613
Reading output/2025-02-05 18:32:44 real-estate-to-rent_real-estate-for-sale.parquet
Total: 55698 valid: 36184 read: 36184 new: 506 deleted: 788 undeleted: 140
Reading output/2025-02-10 14:44:23 real-estate-to-rent_real-estate-for-sale.parquet
Total: 57381 valid: 36042 read: 36042 new: 1683 deleted: 2387 undeleted: 562
Reading output/2025-02-22 13:10:31 real-estate-to-rent_real-estate-for-sale.parquet
Total: 62687 valid: 37449 read: 37449 new: 5306 deleted: 5699 undeleted: 1800
Reading output/2025-03-22 11:44:38 real-estate-to-rent_real-estate-for-sale.parquet
Total: 75232 valid: 38077 read: 38077 new: 12545 deleted: 13216 undeleted: 1299
Reading output/2025-04-05 11:05:29 real-estate-to-rent_real-estate-for-sale.parquet
Total: 81786 valid: 37955 read: 37955 new: 6554 deleted: 10515 undeleted: 3839
Reading output/2025-04-06 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 82008 valid: 37953 read: 37953 new: 222 deleted: 966 undeleted: 742
Reading output/2025-04-07 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 82427 valid: 37898 read: 37898 new: 419 deleted: 1340 undeleted: 866
Reading output/2025-04-08 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 83397 valid: 37981 read: 37981 new: 970 deleted: 2181 undeleted: 1294
Reading output/2025-04-09 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 84321 valid: 38143 read: 38143 new: 924 deleted: 2190 undeleted: 1428
Reading output/2025-04-10 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 85009 valid: 38198 read: 38198 new: 688 deleted: 1490 undeleted: 857
Reading output/2025-04-11 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 85606 valid: 38103 read: 38103 new: 597 deleted: 1979 undeleted: 1287
Reading output/2025-04-12 00:00:01 real-estate-to-rent_real-estate-for-sale.parquet
Total: 86756 valid: 38197 read: 38197 new: 1150 deleted: 2155 undeleted: 1099
Reading output/2025-04-13 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 87140 valid: 38032 read: 38032 new: 384 deleted: 1991 undeleted: 1442
Reading output/2025-04-14 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 87312 valid: 38018 read: 38018 new: 172 deleted: 1521 undeleted: 1335
Reading output/2025-04-15 00:00:01 real-estate-to-rent_real-estate-for-sale.parquet
Total: 88685 valid: 38263 read: 38263 new: 1373 deleted: 2486 undeleted: 1358
Reading output/2025-04-16 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 89392 valid: 38310 read: 38310 new: 707 deleted: 2356 undeleted: 1696
Reading output/2025-04-17 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 89963 valid: 38362 read: 38362 new: 571 deleted: 2663 undeleted: 2144
Reading output/2025-04-18 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 90497 valid: 38221 read: 38221 new: 534 deleted: 1937 undeleted: 1262
Reading output/2025-04-19 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 90668 valid: 38245 read: 38245 new: 171 deleted: 1149 undeleted: 1002
Reading output/2025-04-20 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 90934 valid: 38076 read: 38076 new: 266 deleted: 1381 undeleted: 946
Reading output/2025-04-21 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 91105 valid: 37978 read: 37978 new: 171 deleted: 1086 undeleted: 817
Reading output/2025-04-22 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 91322 valid: 37932 read: 37932 new: 217 deleted: 1948 undeleted: 1685
Reading output/2025-04-23 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 91955 valid: 37903 read: 37903 new: 633 deleted: 3073 undeleted: 2411
Reading output/2025-04-24 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 92450 valid: 37961 read: 37961 new: 495 deleted: 2204 undeleted: 1767
Reading output/2025-04-25 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 93017 valid: 38009 read: 38009 new: 567 deleted: 2271 undeleted: 1752
Reading output/2025-04-28 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 93886 valid: 37758 read: 37758 new: 869 deleted: 3804 undeleted: 2684
Reading output/2025-05-01 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 95633 valid: 38151 read: 38151 new: 1747 deleted: 5083 undeleted: 3729
Reading output/2025-05-04 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 96641 valid: 38072 read: 38072 new: 1008 deleted: 5473 undeleted: 4386
Reading output/2025-05-07 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 98531 valid: 37982 read: 37982 new: 1890 deleted: 5311 undeleted: 3331
Reading output/2025-05-10 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 100130 valid: 38042 read: 38042 new: 1599 deleted: 4540 undeleted: 3001
Reading output/2025-05-13 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 101413 valid: 37990 read: 37990 new: 1283 deleted: 4767 undeleted: 3432
Reading output/2025-05-16 00:00:02 real-estate-to-rent_real-estate-for-sale.parquet
Total: 103424 valid: 38156 read: 38156 new: 2011 deleted: 5933 undeleted: 4088
Reading output/2025-05-19 00:00:01 real-estate-to-rent_real-estate-for-sale.parquet
Total: 104448 valid: 38018 read: 38018 new: 1024 deleted: 3631 undeleted: 2469
Reading output/2025-05-22 00:00:02 real-estate-to-rent_real-estate-for-sale.parquet
Total: 106357 valid: 38352 read: 38352 new: 1909 deleted: 4301 undeleted: 2726
Reading output/2025-05-25 00:00:03 real-estate-to-rent_real-estate-for-sale.parquet
Total: 107606 valid: 38270 read: 38270 new: 1249 deleted: 4249 undeleted: 2918
Reading output/2025-05-28 00:00:03 real-estate-to-rent_real-estate-for-sale.parquet
Total: 109011 valid: 38240 read: 38240 new: 1405 deleted: 4161 undeleted: 2726
Reading output/2025-05-31 00:00:02 real-estate-to-rent_real-estate-for-sale.parquet
Total: 110780 valid: 38501 read: 38501 new: 1769 deleted: 5399 undeleted: 3891
Reading output/2025-06-01 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 111022 valid: 38481 read: 38481 new: 242 deleted: 1531 undeleted: 1269
Reading output/2025-06-04 00:00:03 real-estate-to-rent_real-estate-for-sale.parquet
Total: 113902 valid: 38582 read: 38582 new: 2880 deleted: 7254 undeleted: 4475
Reading output/2025-08-13 10:28:42 real-estate-to-rent_real-estate-for-sale.parquet
Total: 129646 valid: 38115 read: 38115 new: 15744 deleted: 20494 undeleted: 4283
Reading output/2025-08-16 00:00:01 real-estate-to-rent_real-estate-for-sale.parquet
Total: 130700 valid: 37866 read: 37866 new: 1054 deleted: 2179 undeleted: 876
Reading output/2025-08-19 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 131415 valid: 37805 read: 37805 new: 715 deleted: 2116 undeleted: 1340
Reading output/2025-08-22 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 133203 valid: 37856 read: 37856 new: 1788 deleted: 3253 undeleted: 1516
Reading output/2025-08-25 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 134003 valid: 37648 read: 37648 new: 800 deleted: 2542 undeleted: 1534
Reading output/2025-08-28 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 135390 valid: 37975 read: 37975 new: 1387 deleted: 2843 undeleted: 1783
Reading output/2025-08-31 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 136603 valid: 38060 read: 38060 new: 1213 deleted: 3048 undeleted: 1920
Reading output/2025-09-01 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 136786 valid: 38002 read: 38002 new: 183 deleted: 1190 undeleted: 949
Reading output/2025-09-04 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 139014 valid: 38225 read: 38225 new: 2228 deleted: 4038 undeleted: 2033
Reading output/2025-09-07 00:00:02 real-estate-to-rent_real-estate-for-sale.parquet
Total: 140206 valid: 36866 read: 36866 new: 1192 deleted: 3179 undeleted: 628
Reading output/2025-09-10 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 141808 valid: 37352 read: 37352 new: 1602 deleted: 1675 undeleted: 559
Reading output/2025-09-13 00:00:02 real-estate-to-rent_real-estate-for-sale.parquet
Total: 144018 valid: 38731 read: 38731 new: 2210 deleted: 2915 undeleted: 2084
Reading output/2025-09-16 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 144867 valid: 38682 read: 38682 new: 849 deleted: 2261 undeleted: 1363
Reading output/2025-09-19 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 147086 valid: 39070 read: 39070 new: 2219 deleted: 3452 undeleted: 1621
Reading output/2025-09-22 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 148050 valid: 38854 read: 38854 new: 964 deleted: 3154 undeleted: 1974
Reading output/2025-09-25 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 149938 valid: 39086 read: 39086 new: 1888 deleted: 4054 undeleted: 2398
Reading output/2025-09-28 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 151068 valid: 38914 read: 38914 new: 1130 deleted: 3115 undeleted: 1813
Reading output/2025-10-01 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 152371 valid: 38881 read: 38881 new: 1303 deleted: 3258 undeleted: 1922
Reading output/2025-10-04 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 153684 valid: 38682 read: 38682 new: 1313 deleted: 3338 undeleted: 1826
Reading output/2025-10-07 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 154740 valid: 38648 read: 38648 new: 1056 deleted: 3214 undeleted: 2124
Reading output/2025-10-10 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Total: 157366 valid: 38876 read: 38876 new: 2626 deleted: 4412 undeleted: 2014
Reading output/2025-10-14 07:20:23 real-estate-to-rent_real-estate-for-sale.parquet
Total: 158977 valid: 38929 read: 38929 new: 1611 deleted: 4797 undeleted: 3239
Reading output/2025-10-16 00:01:44 real-estate-to-rent_real-estate-for-sale.parquet
Total: 160117 valid: 39066 read: 39066 new: 1140 deleted: 2523 undeleted: 1520
Reading output/2025-10-19 07:29:40 real-estate-to-rent_real-estate-for-sale.parquet
Total: 161314 valid: 38820 read: 38820 new: 1197 deleted: 4483 undeleted: 3040
Reading output/2025-10-22 00:01:58 real-estate-to-rent_real-estate-for-sale.parquet
Total: 162700 valid: 39052 read: 39052 new: 1386 deleted: 3804 undeleted: 2650
Reading output/2025-10-25 00:01:51 real-estate-to-rent_real-estate-for-sale.parquet
Total: 164405 valid: 39138 read: 39138 new: 1705 deleted: 4818 undeleted: 3199
Reading output/2025-10-28 00:01:41 real-estate-to-rent_real-estate-for-sale.parquet
Total: 165222 valid: 39041 read: 39041 new: 817 deleted: 3958 undeleted: 3044
Reading output/2025-10-31 00:01:50 real-estate-to-rent_real-estate-for-sale.parquet
Total: 166294 valid: 39011 read: 39011 new: 1072 deleted: 4219 undeleted: 3117
Reading output/2025-11-01 00:02:19 real-estate-to-rent_real-estate-for-sale.parquet
Total: 166899 valid: 39038 read: 39038 new: 605 deleted: 1571 undeleted: 993
Reading output/2025-11-01 11:23:53 real-estate-to-rent_real-estate-for-sale.parquet
Total: 166986 valid: 38952 read: 38952 new: 87 deleted: 627 undeleted: 454
Reading output/2025-11-04 00:01:41 real-estate-to-rent_real-estate-for-sale.parquet
Total: 167758 valid: 38964 read: 38964 new: 772 deleted: 3689 undeleted: 2929
Reading output/2025-11-07 00:01:37 real-estate-to-rent_real-estate-for-sale.parquet
Total: 169801 valid: 39053 read: 39053 new: 2043 deleted: 5110 undeleted: 3156
Reading output/2025-11-10 00:01:32 real-estate-to-rent_real-estate-for-sale.parquet
Total: 170778 valid: 38858 read: 38858 new: 977 deleted: 4095 undeleted: 2923
Reading output/2025-11-13 00:01:28 real-estate-to-rent_real-estate-for-sale.parquet
Total: 173440 valid: 39215 read: 39215 new: 2662 deleted: 6060 undeleted: 3755
Reading output/2025-11-19 00:01:35 real-estate-to-rent_real-estate-for-sale.parquet
Total: 176129 valid: 39293 read: 39293 new: 2689 deleted: 7710 undeleted: 5099
Reading output/2025-11-22 00:01:24 real-estate-to-rent_real-estate-for-sale.parquet
Total: 178294 valid: 39431 read: 39431 new: 2165 deleted: 5471 undeleted: 3444
Reading output/2025-11-25 00:04:21 real-estate-to-rent_real-estate-for-sale.parquet
Total: 179204 valid: 39374 read: 39374 new: 910 deleted: 3992 undeleted: 3025
Reading output/2025-11-28 00:01:35 real-estate-to-rent_real-estate-for-sale.parquet
Total: 180966 valid: 39432 read: 39432 new: 1762 deleted: 4787 undeleted: 3083
Reading output/2025-12-01 00:01:33 real-estate-to-rent_real-estate-for-sale.parquet
Total: 181747 valid: 39295 read: 39295 new: 781 deleted: 3967 undeleted: 3049
Reading output/2025-12-04 00:01:37 real-estate-to-rent_real-estate-for-sale.parquet
Total: 183235 valid: 39437 read: 39437 new: 1488 deleted: 4499 undeleted: 3153
Reading output/2025-12-07 00:01:32 real-estate-to-rent_real-estate-for-sale.parquet
Total: 184421 valid: 39302 read: 39302 new: 1186 deleted: 5493 undeleted: 4172
Reading output/2025-12-10 00:01:36 real-estate-to-rent_real-estate-for-sale.parquet
Total: 185739 valid: 39304 read: 39304 new: 1318 deleted: 4276 undeleted: 2960
Reading output/2025-12-13 00:01:24 real-estate-to-rent_real-estate-for-sale.parquet
Total: 187769 valid: 39536 read: 39536 new: 2030 deleted: 5867 undeleted: 4069
Reading output/2025-12-16 00:01:40 real-estate-to-rent_real-estate-for-sale.parquet
Total: 188510 valid: 39438 read: 39438 new: 741 deleted: 4104 undeleted: 3265
Reading output/2025-12-19 00:01:32 real-estate-to-rent_real-estate-for-sale.parquet
Total: 189789 valid: 39414 read: 39414 new: 1279 deleted: 4474 undeleted: 3171
Reading output/2025-12-22 00:01:27 real-estate-to-rent_real-estate-for-sale.parquet
Total: 190571 valid: 39186 read: 39186 new: 782 deleted: 4141 undeleted: 3131
Reading output/2025-12-25 00:01:24 real-estate-to-rent_real-estate-for-sale.parquet
Total: 191390 valid: 39034 read: 39034 new: 819 deleted: 4141 undeleted: 3170
Reading output/2026-01-04 19:37:32 real-estate-to-rent_real-estate-for-sale.parquet
Total: 192851 valid: 38406 read: 38406 new: 1461 deleted: 6978 undeleted: 4889
Reading output/2026-01-07 00:37:07 real-estate-to-rent_real-estate-for-sale.parquet
Total: 193340 valid: 38555 read: 38555 new: 489 deleted: 3196 undeleted: 2856
Reading output/2026-01-10 00:37:39 real-estate-to-rent_real-estate-for-sale.parquet
Total: 195084 valid: 38804 read: 38804 new: 1744 deleted: 5992 undeleted: 4497
Reading output/2026-01-13 00:34:06 real-estate-to-rent_real-estate-for-sale.parquet
Total: 195935 valid: 38859 read: 38859 new: 851 deleted: 4775 undeleted: 3979
Reading output/2026-01-16 00:38:34 real-estate-to-rent_real-estate-for-sale.parquet
Total: 197972 valid: 39178 read: 39178 new: 2037 deleted: 4789 undeleted: 3071
Reading output/2026-01-19 00:40:48 real-estate-to-rent_real-estate-for-sale.parquet
Total: 198818 valid: 39092 read: 39092 new: 846 deleted: 4483 undeleted: 3551
Reading output/2026-01-22 00:39:15 real-estate-to-rent_real-estate-for-sale.parquet
Total: 200921 valid: 39331 read: 39331 new: 2103 deleted: 4921 undeleted: 3057
Reading output/2026-01-25 00:42:35 real-estate-to-rent_real-estate-for-sale.parquet

KeyboardInterrupt:

In [7]:
df = pd.read_parquet("/Users/alekseygrachev/git/bazaraki/output/2026-05-27 01:10:46 real-estate-to-rent_real-estate-for-sale.parquet")
df.iloc[0].T

url                                                      https://www.bazaraki.com/adv/6517850_1-bedroom-apartment-to-rent/
title                                                                                          1-bedroom apartment to rent
price                                                                                                              1350.00
original_price                                                                                                         NaN
price_per_sqm                                                                                                          NaN
location                                                                                Limassol, Germasogeia Tourist Area
posted                                                                                                               11:29
ad_id                                                                                                              6517850
reference_number                                                                                                       NaN
views                                                                                                                    5
lat                                                                                                                    NaN
lng                                                                                                                    NaN
sold                                                                                                                 False
posted_dt                                                                                              2026-05-27T11:29:44
cat0                                                                                            Cyprus real estate to rent
cat1                                                                                             Apartments, flats to rent
Reference number                                                                                                      1476
Property area                                                                                                        50.00
Type                                                                                                             Apartment
Floor                                                                                                                  1st
Parking                                                                                                                 No
Furnishing                                                                                                 Fully Furnished
Included                                                                                                 Elevator, Balcony
Online viewing                                                                                                          No
Air conditioning                                                                                           Full, all rooms
Construction year                                                                                                     1995
Energy Efficiency                                                                                                      N/A
Bedrooms                                                                                                                 1
Bathrooms                                                                                                                1
images                 [https://cdn1.bazaraki.com/media/cache1/c9/b3/c9b3d6bab6af7ce258d3f051c8bbb26b.webp, https://cdn...
description            FOR RENT | LIMASSOL – Germasogeia\n1-Bedroom Apartment | Below the Highway | Close to the Del Ma...
Postal code                                                                                                            NaN
Square meter price                                                                                                    None
Pets                                                                                                                  None
Plot area                                                                                                              NaN
Minimum stay                                                                                                          None
Share                                                                                                                 None
Land type                                                                                                             None
Plot Type                                                                                                             None
Parcel number                                                                                                         None
Planning zone                                                                                                         None
Registration block                                                                                                     NaN
Registration number                                                                                                    NaN
Coverage                                                                                                              None
Density                                                                                                               None
Area                                                                                                                   NaN
Condition                                                                                                             None
Property Type                                                                                                         None
Name: 0, dtype: object

In [8]:
df.price_per_sqm = df.price / (df["Property area"]).round(2)

In [9]:
q = "cat1.str.contains('flats to rent', case=False, na=False) and location.str.contains('Limassol, Limassol', case=False, na=False) and description.str.contains('modern', case=False, na=False) and price < 1750"
df.query(q)[df.Floor.isin(['3rd', '5th', '4th', '7th', '8th and above', '6th'])].sort_values("price", ascending=False)

/var/folders/gv/96s0_n4j4xl87r8p93wpnf0r0000gp/T/ipykernel_33804/2413795662.py:2: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.

,url,title,price,original_price,price_per_sqm,location,posted,ad_id,reference_number,views,lat,lng,sold,posted_dt,cat0,cat1,Reference number,Property area,Type,Floor,...,Bathrooms,images,description,Postal code,Square meter price,Pets,Plot area,Minimum stay,Share,Land type,Plot Type,Parcel number,Planning zone,Registration block,Registration number,Coverage,Density,Area,Condition,Property Type
39758,https://www.bazaraki.com/adv/6496960_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,1700.00,NaN,21.25,"Limassol, Limassol - Agia Fyla",20.05.2026 20:25,6496960,NaN,19,NaN,NaN,False,2026-05-20T20:25:00,Cyprus real estate to rent,"Apartments, flats to rent",None,80.00,Apartment,3rd,...,1,"[https://cdn1.bazaraki.com/media/cache1/92/2a/922a84cd30ee2433b1fe4e55d9cdc1c1.webp, https://cdn...","Modern two-bedroom top-floor apartment located in the sought-after area of Agia Fyla, close to t...",NaN,None,Not allowed,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
4398,https://www.bazaraki.com/adv/6483250_3-bedroom-apartment-to-rent/,3-bedroom apartment to rent,1700.00,NaN,14.17,"Limassol, Limassol - Neapolis",15.05.2026 13:09,6483250,NaN,72,NaN,NaN,False,2026-05-15T13:09:00,Cyprus real estate to rent,"Apartments, flats to rent",58319,120.00,Apartment,5th,...,1,"[https://cdn1.bazaraki.com/media/cache1/ee/65/ee654e34926d89bdb010a21ad7ace37b.webp, https://cdn...",Welcome to this spacious 3-bedroom apartment available for rent in the vibrant Neapolis area. Wi...,NaN,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
498,https://www.bazaraki.com/adv/6407225_1-bedroom-apartment-to-rent/,1-bedroom apartment to rent,1700.00,2000.00,26.98,"Limassol, Limassol - Omonia",20.05.2026 11:14,6407225,NaN,216,NaN,NaN,False,2026-05-20T11:14:00,Cyprus real estate to rent,"Apartments, flats to rent",None,63.00,Apartment,3rd,...,1,"[https://cdn1.bazaraki.com/media/cache1/94/89/94899ee0db900d84b2ad3dbc091b26d5.webp, https://cdn...","** The price includes common expenses.\nLuxurious 1-bedroom apartment for rent, featuring modern...",3015.00,None,Not allowed,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
39748,https://www.bazaraki.com/adv/6447211_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,1700.00,NaN,16.67,"Limassol, Limassol - Neapolis",Yesterday 20:10,6447211,NaN,101,NaN,NaN,False,2026-05-26T20:10:44,Cyprus real estate to rent,"Apartments, flats to rent",1395,102.00,Apartment,3rd,...,1,"[https://cdn1.bazaraki.com/media/cache1/4b/96/4b96320d9ed4f2a8e46c2b5cee8622a7.webp, https://cdn...","For long-term, a spacious and modern 2 bedroom spacious apartment located in Neapolis, just behi...",3101.00,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
944,https://www.bazaraki.com/adv/6412788_1-bedroom-apartment-to-rent/,1-bedroom apartment to rent,1700.00,2000.00,26.98,"Limassol, Limassol - Omonia",19.05.2026 12:10,6412788,NaN,18,NaN,NaN,False,2026-05-19T12:10:00,Cyprus real estate to rent,"Apartments, flats to rent",1347,63.00,Apartment,3rd,...,1,"[https://cdn1.bazaraki.com/media/cache1/77/b6/77b6b4e24e7893acbf06d070ae6fd63f.webp, https://cdn...",Luxurious and modern 1-bedroom apartment available for long-term rent in the residential area of...,3015.00,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
9217,https://www.bazaraki.com/adv/6425458_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,1700.00,NaN,17.00,"Limassol, Limassol - Neapolis",28.04.2026 12:49,6425458,NaN,234,NaN,NaN,False,2026-04-28T12:49:00,Cyprus real estate to rent,"Apartments, flats to rent",6777,100.00,Apartment,6th,...,1,"[https://cdn1.bazaraki.com/media/cache1/84/65/84653ef3270d18a57286da3d378d2fdf.webp, https://cdn...","Spacious fully furnished two-bedroom apartment for rent in Neapolis, Limassol, located on the si...",NaN,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
6380,https://www.bazaraki.com/adv/6462951_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,1700.00,NaN,21.25,"Limassol, Limassol - Zakaki",09.05.2026 17:22,6462951,NaN,90,NaN,NaN,False,2026-05-09T17:22:00,Cyprus real estate to rent,"Apartments, flats to rent",None,80.00,Apartment,3rd,...,2,"[https://cdn1.bazaraki.com/media/cache1/00/3f/003fc0d32c3311a811ba70e845261c78.webp, https://cdn...",Modern Two-Bedroom Apartment for Rent in Zakaki\nA stylish and spacious two-bedroom apartment lo...,NaN,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
3328,https://www.bazaraki.com/adv/6504263_2-bedroom-penthouse-to-rent/,2-bedroom penthouse to rent,1700.00,NaN,21.79,"Limassol, Limassol - Agios Georgios",18.05.2026 12:26,6504263,NaN,26,NaN,NaN,False,2026-05-18T12:26:00,Cyprus real estate to rent,"Apartments, flats to rent",31046,78.00,Penthouse,3rd,...,2,"[https://cdn1.bazaraki.com/media/cache1/3c/1d/3c1dc05c1f82cb41ba6480e04517c01b.webp, https://cdn...",Discover this spacious 78 m² penthouse apartment available to rent in the sought-after area of A...,3080.00,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
8333,https://www.bazaraki.com/adv/6442555_2-bedroom-penthouse-to-rent/,2-bedroom penthouse to rent,1650.00,NaN,12.50,"Limassol, Limassol - Petrou Kai Pavlou",01.05.2026 12:47,6442555,NaN,130,NaN,NaN,False,2026-05-01T12:47:00,Cyprus real estate to rent,"Apartments, flats to rent",None,132.00,Penthouse,3rd,...,2,"[https://cdn1.bazaraki.com/media/cache1/20/cd/20cd591e6330eeb7f475405c4ea7cf73.webp, https://cdn...",Spacious Unfurnished Top Floor Apartment in Kapsalos\nTHE APARTMENT IS OFFER UNFURNISHED\nCOMMON...,3081.00,None,Not allowed,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
8083,https://www.bazaraki.com/adv/6250280_3-bedroom-apartment-to-rent/,3-bedroom apartment to rent,1650.00,1800.00,13.75,"Limassol, Limassol - Apostolos Andreas",02.05.2026 12:03,6250280,NaN,116,NaN,NaN,False,2026-05-02T12:03:00,Cyprus real estate to rent,"Apartments, flats to rent",7056,120.00,Apartment,3rd,...,2,"[https://cdn1.bazaraki.com/media/cache1/20/0e/200e29a1a30be70d895f8870991717de.webp, https://cdn...",Welcome to this spacious 120 m² top-floor apartment available for rent in the sought-after area ...,NaN,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
4686,https://www.bazaraki.com/adv/6403611_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,1650.00,NaN,17.74,"Limassol, Limassol - Kapsalos",14.05.2026 18:07,6403611,NaN,61,NaN,NaN,False,2026-05-14T18:07:00,Cyprus real estate to rent,"Apartments, flats to rent",29596,93.00,Apartment,3rd,...,1,"[https://cdn1.bazaraki.com/media/cache1/86/5b/865bfc751fe64a35a52c93d567f72179.webp, https://cdn...",THE APARTMENT IS OFFER UNFURNISHED\nCOMMON EXPENSES INCLUDED IN THE PRICE\n2 VERANDAS\nENSUITE S...,3077.00,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
4269,https://www.bazaraki.com/adv/6224021_2-bedroom-penthouse-to-rent/,2-bedroom penthouse to rent,1650.00,NaN,10.00,"Limassol, Limassol - Kapsalos",15.05.2026 21:44,6224021,NaN,349,NaN,NaN,False,2026-05-15T21:44:00,Cyprus real estate to rent,"Apartments, flats to rent",29596,165.00,Penthouse,3rd,...,2,"[https://cdn1.bazaraki.com/media/cache1/e9/1c/e91cec8992d920c9d50ad778687b740b.webp, https://cdn...",The apartment is offer unfurnished\nCommon expenses included in the price\n2 verandas\nEnsuite s...,NaN,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
3166,https://www.bazaraki.com/adv/6504723_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,1650.00,NaN,20.62,"Limassol, Limassol - Omonia",18.05.2026 15:55,6504723,NaN,54,NaN,NaN,False,2026-05-18T15:55:00,Cyprus real estate to rent,"Apartments, flats to rent",None,80.00,Apartment,3rd,...,1,"[https://cdn1.bazaraki.com/media/cache1/18/b9/18b933ad2a855e4fc1cf1f58d7a42ec2.webp, https://cdn...","In an exclusive residential complex of just seven apartments, this stylish two-bedroom, one-bath...",NaN,None,Not allowed,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
1821,https://www.bazaraki.com/adv/6375193_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,1650.00,NaN,20.62,"Limassol, Limassol - Omonia",25.04.2026 15:18,6375193,NaN,121,NaN,NaN,False,2026-04-25T15:18:00,Cyprus real estate to rent,"Apartments, flats to rent",25138,80.00,Apartment,3rd,...,1,"[https://cdn1.bazaraki.com/media/cache1/28/2c/282ca2c04e876b48e9c391a3f706732d.webp, https://cdn...",Welcome to this inviting two-bedroom apartment situated in the vibrant area of Omonoia. Spanning...,3012.00,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
451,https://www.bazaraki.com/adv/6205748_3-bedroom-penthouse-to-rent/,3-bedroom penthouse to rent,1610.00,NaN,10.73,"Limassol, Limassol - Agios Ioannis",Yesterday 13:53,6205748,NaN,1027,NaN,NaN,False,2026-05-26T13:53:44,Cyprus real estate to rent,"Apartments, flats to rent",None,150.00,Penthouse,3rd,...,2,"[https://cdn1.bazaraki.com/media/cache1/95/66/9566b0a9ddb01ac88919ed095aa705d2.webp, https://cdn...","✨ 3-Bedroom Penthouse for Rent in Agios Ioannis, Limassol ✨\n🔑 Property Features:\nFully-Furnis...",NaN,None,Allowed,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
7851,https://www.bazaraki.com/adv/6084222_2-bedroom-apartment-to-rent/,2-bedroom penthouse to rent,1610.00,NaN,14.64,"Limassol, Limassol - Linopetra",05.05.2026 11:32,6084222,NaN,1817,NaN,NaN,False,2026-05-05T11:32:00,Cyprus real estate to rent,"Apartments, flats to rent",None,110.00,Penthouse,3rd,...,2,"[https://cdn1.bazaraki.com/media/cache1/29/b4/29b4e4ffa44001217d26d2c0ce0fddb4.webp, https://cdn...","✨ 2 Bedrooms Penthouse 301, for Rent in Linopetra, Limassol ✨\n🔑 Property Features:\nFurnished ...",NaN,None,Allowed,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
39304,https://www.bazaraki.com/adv/6475726_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,1600.00,NaN,15.69,"Limassol, Limassol - Agios Nicolaos",20.05.2026 18:01,6475726,NaN,101,NaN,NaN,False,2026-05-20T18:01:00,Cyprus real estate to rent,"Apartments, flats to rent",2472,102.00,Apartment,5th,...,1,"[https://cdn1.bazaraki.com/media/cache1/29/93/299354d4ec51a4966bf0cfdcf3acd78b.webp, https://cdn...","A comfortable and convenient apartment in the heart of the city. Situated in a prime location, t...",NaN,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
39707,https://www.bazaraki.com/adv/6066106_3-bedroom-apartment-to-rent/,3-bedroom apartment to rent,1600.00,1900.00,14.68,"Limassol, Limassol - Apostolos Andreas",22.04.2026 21:23,6066106,NaN,138,NaN,NaN,False,2026-04-22T21:23:00,Cyprus real estate to rent,"Apartments, flats to rent",23996,109.00,Apartment,3rd,...,1,"[https://cdn1.bazaraki.com/media/cache1/8b/db/8bdbfda4499e88d632ad879b2c3a2055.webp, https://cdn...",Welcome to this bright and spacious top-floor apartment available for rent in the sought-after a...,3066.00,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
39151,https://www.bazaraki.com/adv/6448588_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,1600.00,1800.00,16.84,"Limassol, Limassol - Zakaki",21.05.2026 12:21,6448588,NaN,234,NaN,NaN,False,2026-05-21T12:21:00,Cyprus real estate to rent,"Apartments, flats to rent",None,95.00,Apartment,3rd,...,2,"[https://cdn1.bazaraki.com/media/cache1/9f/f4/9ff4b58ae6d01d9af065cd0b8ba92386.webp, https://cdn...","🏡 Brand New Apartment – 2025 Construction\nA modern and stylish apartment, fully equipped and id...",NaN,None,Allowed,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
39593,https://www.bazaraki.com/adv/6507827_3-bedroom-apartment-to-rent/,3-bedroom apartment to rent,1550.00,NaN,12.40,"Limassol, Limassol - Katholiki",10:48,6507827,NaN,8,NaN,NaN,False,2026-05-27T10:48:44,Cyprus real estate to rent,"Apartments, flats to rent",None,125.00,Apartment,3rd,...,2,"[https://cdn1.bazaraki.com/media/cache1/b6/34/b6341c2c7f929afc1ce1ca548ceebf3c.webp, https://cdn...","Fully furnished 3-bedroom apartment in Katholiki, Limassol\nRecently fully renovated modern apar...",3025.00,None,Allowed,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
39699,https://www.bazaraki.com/adv/6468533_3-bedroom-apartment-to-rent/,3-bedroom apartment to rent,1550.00,NaN,12.40,"Limassol, Limassol - Katholiki",12.05.2026 10:59,6468533,NaN,182,NaN,NaN,False,2026-05-12T10:59:00,Cyprus real estate to rent,"Apartments, flats to rent",None,125.00,Apartment,3rd,...,2,"[https://cdn1.bazaraki.com/media/cache1/0a/10/0a10424256f34bff1d9f145b9754910d.webp, https://cdn...",Fully furnished three bedroom appartment recently removated located in a very central part of Ka...,3025.00,None,Allowed,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
6845,https://www.bazaraki.com/adv/6289346_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,1550.00,NaN,17.42,"Limassol, Limassol - Tsiflikoudia",07.05.2026 18:02,6289346,NaN,299,NaN,NaN,False,2026-05-07T18:02:00,Cyprus real estate to rent,"Apartments, flats to rent",APA_11244,89.00,Apartment,3rd,...,1,"[https://cdn1.bazaraki.com/media/cache1/f6/f2/f6f21c49f20d4c2967b42ec53df04844.webp, https://cdn...","2 Bedrooms | 1 Bathroom + Guest WC | Air Conditioning\nLocated in a private, exclusive residenti...",NaN,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
5412,https://www.bazaraki.com/adv/6466879_3-bedroom-apartment-to-rent/,3-bedroom apartment to rent,1500.00,NaN,12.00,"Limassol, Limassol - Kapsalos",12.05.2026 09:19,6466879,NaN,151,NaN,NaN,False,2026-05-12T09:19:00,Cyprus real estate to rent,"Apartments, flats to rent",EV-148572-property,125.00,Apartment,3rd,...,2,"[https://cdn1.bazaraki.com/media/cache1/19/f2/19f2cb0c2f09c8e7e76eb25e70368c7c.webp, https://cdn...",Bright &amp; Spacious 3-Bedroom Top-Floor Apartment – Kapsalos\nLocated in the highly sought-aft...,NaN,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
1367,https://www.bazaraki.com/adv/6516587_1-bedroom-apartment-to-rent/,1-bedroom apartment to rent,1500.00,NaN,30.00,"Limassol, Limassol - Neapolis",15:34,6516587,NaN,0,NaN,NaN,False,2026-05-27T15:34:44,Cyprus real estate to rent,"Apartments, flats to rent",None,50.00,Apartment,4th,...,1,"[https://cdn1.bazaraki.com/media/cache1/3d/f6/3df68377f0da3fc04469764d5e59f9e4.webp, https://cdn...","appartment is under renovation!\nOne Bedroom Apartment in Neapoli\nModern, renovated one-bedroom...",NaN,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
75,https://www.bazaraki.com/adv/6502705_1-bedroom-apartment-to-rent/,1-bedroom apartment to rent,1350.00,NaN,18.24,"Limassol, Limassol - Apostolos Andreas",20:30,6502705,NaN,69,NaN,NaN,False,2026-05-27T20:30:44,Cyprus real estate to rent,"Apartments, flats to rent",None,74.00,Apartment,4th,...,1,"[https://cdn1.bazaraki.com/media/cache1/a7/ff/a7ff1eaaab4617986d1aafcd4950b4ba.webp, https://cdn...",✨ Brand New Fully Furnished 1-Bedroom Apartment\nBeautiful brand new 1-bedroom apartment for ren...,3066.00,None,Not allowed,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
783,https://www.bazaraki.com/adv/6518810_1-bedroom-apartment-to-rent/,1-bedroom apartment to rent,1300.00,NaN,19.40,"Limassol, Limassol - Tsirion",15:45,6518810,NaN,8,NaN,NaN,False,2026-05-27T15:45:44,Cyprus real estate to rent,"Apartments, flats to rent",None,67.00,Apartment,3rd,...,1,"[https://cdn1.bazaraki.com/media/cache1/fd/d2/fdd2ac994adae88cba91b007b15722b1.webp, https://cdn...",Modern 1-Bedroom Apartment for Rent in Limassol - Fully Furnished\nA fantastic opportunity to re...,NaN,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
4218,https://www.bazaraki.com/adv/6406869_1-bedroom-apartment-to-rent/,1-bedroom apartment to rent,1200.00,NaN,27.27,"Limassol, Limassol - Neapolis",16.05.2026 15:03,6406869,NaN,108,NaN,NaN,False,2026-05-16T15:03:00,Cyprus real estate to rent,"Apartments, flats to rent",30658,44.00,Apartment,3rd,...,1,"[https://cdn1.bazaraki.com/media/cache1/9e/33/9e33ccb610a8469d9c0556b67bc1b065.webp, https://cdn...",Available from 25th of April.\nWelcome to this bright and comfortable one-bedroom apartment avai...,3101.00,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None
3227,https://www.bazaraki.com/adv/6506430_3-bedroom-apartment-to-rent/,3-bedroom apartment to rent,1200.00,NaN,12.63,"Limassol, Limassol - Tsirion",19.05.2026 15:14,6506430,NaN,74,NaN,NaN,False,2026-05-19T15:14:00,Cyprus real estate to rent,"Apartments, flats to rent",7412,95.00,Apartment,4th,...,2,"[https://cdn1.bazaraki.com/media/cache1/68/24/68245b3e02dbbecf7c6f40dd13402c1f.webp, https://cdn...",Available now for rent is a spacious 95 m² apartment located on the top floor of a well-maintain...,NaN,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None

In [ ]:
saledf = df[df.cat1.isin(['Apartments, flats for sale'])]
saledf.iloc

In [ ]:
saledf

,url,title,price,original_price,price_per_sqm,location,posted,ad_id,reference_number,views,lat,lng,sold,posted_dt,cat0,cat1,Reference number,Property area,Type,Parking,...,Pets,Floor,Furnishing,Online viewing,Plot area,Postal code,Square meter price,Land type,Plot Type,Share,Condition,Minimum stay,Planning zone,Density,Coverage,Parcel number,Registration block,Registration number,Area,Property Type
8342,https://www.bazaraki.com/adv/6361585_1-bedroom-apartment-for-sale/,1-bedroom apartment for sale,99000.00,NaN,2062.50,"Nicosia, Palouriotissa",Yesterday 15:07,6361585,NaN,61,NaN,NaN,False,2026-03-18T15:07:49,Cyprus real estate for sale,"Apartments, flats for sale",3011,48.00,Apartment,Covered,...,None,None,None,No,NaN,NaN,€2.063 /,None,None,None,Resale,None,None,None,None,None,NaN,NaN,NaN,None
8344,https://www.bazaraki.com/adv/6361605_2-bedroom-apartment-for-sale/,2-bedroom apartment for sale,192000.00,NaN,2400.00,"Nicosia, Palouriotissa",Yesterday 14:13,6361605,NaN,12,NaN,NaN,False,2026-03-18T14:13:49,Cyprus real estate for sale,"Apartments, flats for sale",None,80.00,Apartment,Covered,...,None,3rd,Unfurnished,No,NaN,NaN,€2.400 /,None,None,None,Under construction,None,None,None,None,None,NaN,NaN,NaN,None
8350,https://www.bazaraki.com/adv/5975601_3-bedroom-penthouse-for-sale/,3-bedroom penthouse for sale,545000.00,NaN,1735.67,"Paphos, Paphos - Agios Theodoros",Yesterday 18:31,5975601,NaN,779,NaN,NaN,False,2026-03-18T18:31:49,Cyprus real estate for sale,"Apartments, flats for sale",None,314.00,Penthouse,Covered,...,None,3rd,Semi-Furnished,Yes,NaN,8046.00,€1.736 /,None,None,None,Brand new,None,None,None,None,None,NaN,NaN,NaN,None
8352,https://www.bazaraki.com/adv/6362233_2-bedroom-apartment-for-sale/,2-bedroom apartment for sale,195000.00,NaN,2191.01,"Larnaca, Aradippou - Agios Fanourios",Yesterday 18:53,6362233,NaN,7,NaN,NaN,False,2026-03-18T18:53:49,Cyprus real estate for sale,"Apartments, flats for sale",None,89.00,Apartment,Covered,...,None,1st,Unfurnished,No,NaN,7101.00,€2.191 /,None,None,None,Under construction,None,None,None,None,None,NaN,NaN,NaN,None
8354,https://www.bazaraki.com/adv/6130987_1-bedroom-apartment-for-sale/,1-bedroom apartment for sale,218000.00,NaN,4360.00,"Limassol, Trachoni Lemesou",Yesterday 19:23,6130987,NaN,61,NaN,NaN,False,2026-03-18T19:23:49,Cyprus real estate for sale,"Apartments, flats for sale",None,50.00,Apartment,Uncovered,...,None,3rd,Unfurnished,No,NaN,NaN,€4.360 /,None,None,None,Brand new,None,None,None,None,None,NaN,NaN,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39241,https://www.bazaraki.com/adv/6360222_2-bedroom-penthouse-for-sale/,2-bedroom penthouse for sale,335000.00,NaN,4187.50,"Famagusta, Pernera",17.03.2026 17:10,6360222,NaN,51,NaN,NaN,False,2026-03-17T17:10:00,Cyprus real estate for sale,"Apartments, flats for sale",None,80.00,Penthouse,Covered,...,None,2nd,Fully Furnished,Yes,NaN,NaN,€4.188 /,None,None,None,Resale,None,None,None,None,None,NaN,NaN,NaN,None
39243,https://www.bazaraki.com/adv/6360482_1-bedroom-apartment-for-sale/,1-bedroom apartment for sale,139000.00,NaN,2138.46,"Larnaca, Livadia Larnakas",17.03.2026 19:40,6360482,NaN,90,NaN,NaN,False,2026-03-17T19:40:00,Cyprus real estate for sale,"Apartments, flats for sale",None,65.00,Apartment,Covered,...,None,1st,Unfurnished,Yes,NaN,NaN,€2.138 /,None,None,None,Under construction,None,None,None,None,None,NaN,NaN,NaN,None
39248,https://www.bazaraki.com/adv/5574187_2-bedroom-apartment-for-sale/,2-bedroom apartment for sale,210000.00,NaN,2560.98,"Nicosia, Strovolos - Stavros",Yesterday 05:44,5574187,NaN,623,NaN,NaN,False,2026-03-18T05:44:49,Cyprus real estate for sale,"Apartments, flats for sale",None,82.00,Apartment,Covered,...,None,2nd,Unfurnished,No,NaN,2035.00,€2.561 /,None,None,None,Under construction,None,None,None,None,None,NaN,NaN,NaN,None
39249,https://www.bazaraki.com/adv/5723441_2-bedroom-apartment-for-sale/,2-bedroom apartment for sale,182000.00,NaN,1838.38,"Nicosia, Lakatameia - Agia Paraskevi",Yesterday 05:45,5723441,NaN,2829,NaN,NaN,False,2026-03-18T05:45:49,Cyprus real estate for sale,"Apartments, flats for sale",None,99.00,Apartment,Covered,...,None,1st,Unfurnished,No,NaN,2311.00,€1.838 /,None,None,None,Under construction,None,None,None,None,None,2.00,10785.00,NaN,None
39252,https://www.bazaraki.com/adv/4772494_2-bedroom-apartment-for-sale/,2-bedroom apartment for sale,122500.00,NaN,1200.98,"Famagusta, Paralimni",Yesterday 11:39,4772494,NaN,1034,NaN,NaN,False,2026-03-18T11:39:49,Cyprus real estate for sale,"Apartments, flats for sale",None,102.00,Apartment,Covered,...,None,Ground floor,Fully Furnished,No,NaN,5289.00,€1.201 /,None,None,None,Resale,None,None,None,None,None,NaN,NaN,NaN,None

In [ ]:
q = "description.str.contains('rented', case=False, na=False) and location.str.contains('Limassol, Limassol', case=False, na=False) and price < 500000 and Condition == 'Resale' and price_per_sqm < 4000"
saledf.query(q).sort_values(by=["price_per_sqm"])[["posted", "price", "price_per_sqm", "Construction year", "location", "url"]]

,posted,price,price_per_sqm,Construction year,location,url
31630,28.02.2026 09:13,345000.00,2284.77,1996,"Limassol, Limassol - Mesa Geitonia",https://www.bazaraki.com/adv/6226692_2-bedroom-penthouse-for-sale/
16942,12.03.2026 15:19,260000.00,2476.19,None,"Limassol, Limassol - Agia Zoni",https://www.bazaraki.com/adv/6351705_3-bedroom-apartment-for-sale/
10573,17.03.2026 17:53,300000.00,2500.00,2010,"Limassol, Limassol - Petrou Kai Pavlou",https://www.bazaraki.com/adv/6360336_3-bedroom-apartment-for-sale/
25225,06.03.2026 14:23,245000.00,2722.22,2023,"Limassol, Limassol - Agia Zoni",https://www.bazaraki.com/adv/6329360_studio-apartment-for-sale/
26350,04.03.2026 20:52,345000.00,2760.00,1998,"Limassol, Limassol - Neapolis",https://www.bazaraki.com/adv/6332956_3-bedroom-apartment-for-sale/
27025,04.03.2026 14:40,349000.00,2908.33,1998,"Limassol, Limassol - Neapolis",https://www.bazaraki.com/adv/6331395_3-bedroom-apartment-for-sale/
21712,09.03.2026 14:56,349000.00,2908.33,1998,"Limassol, Limassol - Neapolis",https://www.bazaraki.com/adv/6345507_3-bedroom-apartment-for-sale/
20585,10.03.2026 13:40,285000.00,3000.00,None,"Limassol, Limassol - Agios Ioannis",https://www.bazaraki.com/adv/6347029_2-bedroom-apartment-for-sale/
38336,12.03.2026 14:58,285000.00,3000.00,2012,"Limassol, Limassol - Agios Ioannis",https://www.bazaraki.com/adv/6351129_2-bedroom-apartment-for-sale/
27035,04.03.2026 14:46,290000.00,3020.83,2014,"Limassol, Limassol - Zakaki",https://www.bazaraki.com/adv/6331449_2-bedroom-apartment-for-sale/
10633,17.03.2026 22:21,280000.00,3111.11,Older,"Limassol, Limassol - Neapolis",https://www.bazaraki.com/adv/6327735_2-bedroom-apartment-for-sale/
18158,11.03.2026 21:02,178000.00,3236.36,Older,"Limassol, Limassol - Agia Triada",https://www.bazaraki.com/adv/6129045_studio-apartment-for-sale/
25481,06.03.2026 08:00,249000.00,3276.32,None,"Limassol, Limassol - Agios Nicolaos",https://www.bazaraki.com/adv/6069699_2-bedroom-apartment-for-sale/
12416,16.03.2026 14:54,280000.00,3500.00,2025,"Limassol, Limassol - Neapolis",https://www.bazaraki.com/adv/6230979_2-bedroom-apartment-for-sale/
26493,04.03.2026 20:28,280000.00,3500.00,2025,"Limassol, Limassol - Neapolis",https://www.bazaraki.com/adv/6236819_2-bedroom-apartment-for-sale/
32014,27.02.2026 17:15,249000.00,3557.14,2006,"Limassol, Limassol - Agia Zoni",https://www.bazaraki.com/adv/6313679_2-bedroom-apartment-for-sale/
12142,16.03.2026 17:08,399000.00,3627.27,None,"Limassol, Limassol - Petrou Kai Pavlou",https://www.bazaraki.com/adv/6053922_3-bedroom-apartment-for-sale/
11713,16.03.2026 21:01,399000.00,3627.27,Older,"Limassol, Limassol - Petrou Kai Pavlou",https://www.bazaraki.com/adv/6023860_3-bedroom-apartment-for-sale/
18777,11.03.2026 12:31,350000.00,3763.44,2010,"Limassol, Limassol - Mesa Geitonia",https://www.bazaraki.com/adv/5926321_2-bedroom-apartment-for-sale/

In [ ]:
q = "description.str.contains('rented', case=False, na=False) and location.str.contains('Limassol', case=False, na=False) and price < 500000 "
saledf.query(q)[["posted", "price", "url", "description"]]

,posted,price,url,description
8530,Yesterday 21:16,448000,https://www.bazaraki.com/adv/6215994_2-bedroom-apartment-for-sale/,"Modern 2-Bedroom Apartment for Sale in Germasogeia\nLocated on the 1st floor of a contemporary residential building, this stylish 2-bedroom apartment offers a total internal area of 83 m² plus a spacious 32 m² covered veranda, ideal for comfortable indoor–outdoor living.\nThe property features:\n• \tModern open-plan layout\n• \tUnderfloor heating\n• \tAir conditioning throughout\n• \tOne bathroom with a bathtub, plus a w.c\n• \tAutomatic blinds\n• \tFully equipped kitchen with appliances\n• \tReinforced, soundproofed windows\n• \tCommunal swimming pool and landscaped garden\n• \tOutdoor parking space\n• \tPrivate storage room\nThe apartment is currently rented for €1,750 per month plus common expenses, offering an immediate rental return.\nPrice: €448.000\nTitle deeds available"
9957,23.02.2026 18:19,178000,https://www.bazaraki.com/adv/6129045_studio-apartment-for-sale/,Investment Opportunity\n1200 rented\nStudio for rent\nOld Town\nMolos\nWalking distance to the sea\nFully furnished\nGround floor
10055,23.02.2026 11:27,330000,https://www.bazaraki.com/adv/5839332_2-bedroom-apartment-for-sale/,"Introducing this 2-bedroom apartment in the desirable Agia Triada area of Limassol, an excellent investment opportunity for buyers and investors alike.\nThis apartment offers a cozy living room, a separate kitchen, two bedrooms, one bathroom, and two verandas.\nPerfectly situated in the city center with a walking distance from the beach, the apartment provides easy access to schools, banks, and essential amenities, ensuring a convenient and luxurious lifestyle.\nSpecifications:\n- Covered Area: 85m2\n- Covered Veranda: 21m2\n- Uncovered Veranda: 5m2\nPrice: €330.000 (No VAT)\nIts currently rented at €1400. Contact us today for detailed information!"
10405,23.02.2026 02:26,310000,https://www.bazaraki.com/adv/5838519_2-bedroom-apartment-for-sale/,"Introducing this 2-bedroom apartment in the Mesa Geitonia area of Limassol, an excellent investment opportunity for both buyers and investors.\nThis well-designed apartment features a living room seamlessly connected to kitchen, two comfortable bedrooms, two bathrooms, and a lovely veranda. Currently, the property is rented and used as an office, offering immediate rental income potential.\nPerfectly positioned just 5 minutes from both the city center and the highway, it provides excellent access to schools, banks, shops, and other essential amenities.\nSpecifications:\n- Covered Area: 74m2\n- Covered Veranda: 9m2\nPrice: €310,000 (No VAT)\nContact us for a viewing."
11058,22.02.2026 09:10,278000,https://www.bazaraki.com/adv/6050887_3-bedroom-apartment-for-sale/,"Spacious 3-Bedroom Apartment for Sale in in Agia Fyla, Limassol, Cyprus\nLocation:\nLocated in the vibrant area of Agia Fyla, the property combines urban convenience with residential comfort. Its central position ensures quick access to shops, schools, services, and the city’s main roads, while the covered verandas with sea view offer a relaxing living environment. Whether used as a family residence or adapted for rental purposes, the apartment offers an excellent balance of comfort and practicality.\nAn exceptional opportunity to acquire a large three-bedroom apartment located in the highly sought-after area of Agia Fyla, Limassol. Offering both size and versatility, this property is ideally suited for investors or families looking for a central residence with strong rental potential.\nProperty Details:\nInternal area: 116 sq.m\nAdditional space: 2 covered verandas with sea view\nLayout: 3 bedrooms, 1 bathroom, 2 toilets\nParking: Uncovered parking space\nBuilding features: Elevator\nInvestment Highlights:\nThe apartment can be easily divided into two spacious units of approximately 60 sq.m each.\nEstimated rental income after division: approximately €3,000 per month.\nCurrently rented as a single apartment for €1,600 per month.\nWhy Invest:\nWith its spacious layout, high rental yield potential, and flexible floor plan, this apartment represents a rare investment opportunity in Limassol. Investors benefit from immediate rental income with the option to significantly increase returns by dividing the property, while homeowners can enjoy the advantages of a prime location and a lifestyle close to the city’s amenities.\nPrice: €278,000\nContact Us:\nFor further details or to arrange a private viewing, please do not hesitate to get in touch.\nOur team will be happy to provide additional information and guide you through the process of securing this excellent property."
11083,22.02.2026 10:12,250000,https://www.bazaraki.com/adv/6300060_2-bedroom-apartment-for-sale/,"Excellent Investment Opportunity!\nSpacious 2 Bedroom Apartment For Sale in Neapoli, Limassol with Title Deeds\nPrime location, just a few steps from the Agios Nikolaos junction, amenites and the seafront\nIt boasts quick and easy access to the core of the city center and the prestigious Limassol Marina! Only 300 meters From The Sea.\n1st Floor\n2 Bedrooms, Currently convereted in to an open plan office space\n1 Bathroom + 1 Guest W/C\n70m2 of Net Indoor area\n10m2 of Covered Veranda\nUncovered Parking\nA/C\nFitted Kitchen\nOpen Plan\nElevator\nLobby\nYear of Build: 1979\nRenovated with modern design and materials\nThis apartment is a captivating investment opportunity!\nIt is currently rented to quality tenants, generating a high and secure ROI\nIt is excellent for permanent living for a couple\nContact us for full information and a private viewing"
11726,21.02.2026 12:26,250000,https://www.bazaraki.com/adv/5915257_2-bedroom-apartment-for-sale/,"Prime Investment — Limassol\nGuaranteed income: Rented to one of the biggest hotel groups in Cyprus at a 7% yield for the next 3 years (they intend to stay longer).\nTop location: 250 m from the beach, opposite the Four Seasons Hotel, in the prime tourist area.\nWhy it’s a great buy:\n*High monthly income: 7–8% yield potential\n*High demand for long-term rent\n*Perfect for Airbnb and short stays\n*Exceptionally large, fully renovated 2-bedroom apartment\n*Huge covered balcony with glass enclosure\n*Turn-key: sold fully furnished with new furniture & appliances\n*A/C in every room\n*Appliances included: full kitchen setup, washing machine, 50"" Android TV\n*Private, gated parking space\n*Walk to everything: beach, shops, cafés, restaurants, attractions\n*Paperwork: Title deed available\nPlease send whatsapp only"
11870,21.02.2026 15:38,300000,https://www.bazaraki.com/adv/6298070_2-bedroom-apartment-for-sale/,"Exceptional 80 sq.m. two-bedroom apartment in the heart of Limassol, located on a side street just off Makariou Avenue, right next to Costa Coffee.\nPositioned on the 4th floor, the apartment enjoys lovely sea views and an abundance of natural light. It is partially furnished and fully equipped with all electrical appliances, featuring air conditioning throughout and a covered veranda—perfect for relaxing.\nSet in one of Limassol’s most sought-after central areas, the property is within walking distance of shops, services, restaurants, and cafés, offering the ultimate convenience of city living.\nAn excellent investment opportunity: the apartment is currently rented at €1,300 per month, with proven potential to achieve €1,400 or more, making it an attractive option for investors seeking strong and reliable rental returns."
12019,21.02.2026 17:09,450000,https://www.bazaraki.com/adv/4671117_2-bedroom-apartment-for-sale/,"Reference ID: #SA30738\nPrice details: €450,000\nProject located in Yermasogeia area, Limassol district.\nThis project explores a different type of urban development model comprising of mixed scale residential units.\nThe apartment building is comprised of three volumes of 4 levels that house 23 apartments of one, two and three bedrooms.\nThe last level of block C is a four bedroom penthouse with internal access to the roof garden. With contemporary interior design this penthouse captures the essence of achieving a secluded place where its residents can indulge in an exclusive living experience.\nSubsequently, the design manages to distill a feeling of privacy and luxury that is usually reserved for the single family house or for large scale loft styling living.\nBuilding combines contemporary architecture with luxury living spaces and innovative sky gardens.\nPatios and green terraces multiplied from ground level upwards with elements found in the natural world such as mountaintop views, sea views and green terraces all combine to provide an easy entirely natural and relaxing landscape for the residents, allowing the whole development the luxury of natural ventilation, sunlight and a feeling of open space on all sides.\n2 Bedroom : From 89 sqm internal plus 26 balconies\n3 bedroom : From101 sqm internal plus 32 balconies\nPenthouse : From 146 sqm internal plus 69 balconies\nWhole project area:\nCovered Area: 2311sqm (internal)\n719sqm covered balconies\n301sqm Circulation Area\nCovered Garden : 324sqm\nBuilt Area: 2,658 m2\nThe Apartments are rented with monthly ammount €2000-€3500"
12377,20.02.2026 20:13,493000,https://www.bazaraki.com/adv/6062288_4-bedroom-apartment-for-sale/,"Reference ID: #GE5057Price details: €493,000The building is centrally (Columbia) located and close to the entrance of Limassol, with countless amenities(supermarkets, schools, shops pharmacy,etc) and just minutes from the beach. The apartment offers a contemporary open plan combined lounge and dining, modern kitchen, large balcony, 3 double bedrooms with built in ward- robes (main with ensuite), guest WC, large family bathroom and a massive roof deck with great views which is ideal for entertaining. In addition to this, the property is offered with a separate self contained apartment with 2 rooms and a bathroom on the ground floor. This separate apartment could be rented out and offer a great extraincome. -3 bedroom penthouse(120sq+8sm balcony) + 1 bedroom apartment in the basement floor(42sq) -Columbia area germasogeia -125 sq+10sq veranda -Huge roof garden!! - 2 covered parking spaces"
13302,20.02.2026 08:23,285000,https://www.bazaraki.com/adv/6214934_2-bedroom-apartment-for-sale/,"For sale, a recently renovated, spacious 2-bedroom flat with an 81sqm + 6sqm balcony in Germasoyia tourist area near Del-Mar and Metro Supermarket.\nThe flat is renovated and fully furnished. Located on the 3rd floor (top floor) with a side sea view from both ends—a minute walk to the sandy beach.\n📍Top location📍\nThe flat consists of a separate, wide kitchen with new electric appliances included. Plus, a dishwasher.\n✅ Renovated & Furnished\n✅ New electric appliances\n✅ Amazing side sea view\n✅ A/C everywhere\n✅ Double-glazed windows\n✅ Solar heating system\n✅ Water pressure pump\n✅ Uncovered parking\n✅ Elevator\n✅ Opposite the beach!\nTitle deed available.\nCurrently rented out on an annual lease for 1,500 euros monthly.\nExcellent investment opportunity with good ROI 💹"
14912,19.02.2026 08:35,273000,https://www.bazaraki.com/adv/5688661_2-bedroom-penthouse-for-sale/,"A nearly new, fully furnished one-year-old flat is available for sale in a quiet area of Asomatos. Featuring high-quality finishes and modern appliances, it offers both comfort and style. The property is currently rented at €1,350 per month until March 2026."
15628,18.02.2026 14:26,230000,https://www.bazaraki.com/adv/6286741_1-bedroom-apartment-for-sale/,"1 bedroom apartment for sale in Agios Tychon, opposite Four Seasons Hotel. Located just 200m from the beach with all amenities nearby.\n- 1 bedroom\n- 1 bathroom\n- walking distance to the beach\n- currently rented to a tenant\n- great ROI 7%\n- renovated apartment\nGet in contact now !\nUnder the Authorization of the licensed Real Estate Agent: KW Seven - Gold Seven Real Estate Agency Ltd\nLicense No. 366/E Reg. No. 772"
17770,16.02.2026 20:38,385000,https://www.bazaraki.com/adv/6009633_2-bedroom-apartment-for-sale/,"Discover this beautifully renovated ground-floor apartment for sale in the popular area of Neapolis. With 70 m2 of internal space, this modern home features two comfortable bedrooms and one stylish bathroom. Fully furnished, it's ready for you to move in and start enjoying right away. The recent 2024 renovation included high-quality materials and smart, modern design, while the building itself dates back to 1985, giving it solid structure and timeless charm.\nCurrently rented with a 6% ROI.\nLocated in Neapolis, you will be close to a wide variety of shops, cafes, and restaurants. The area is known for its vibrant atmosphere, excellent amenities, and easy access to public transportation. Green parks and the beachfront are only a short walk away, making this an ideal spot for both relaxation and convenience.\nThis apartment boasts energy efficiency class A, ensuring lower utility costs and a comfortable living environment all year round. Perfect for professionals, small families, or as a smart investment opportunity.\nFor more information or to schedule a viewing, contact Nest & Co today. This is your chance to own a modern, hassle-free apartment in one of the most sought-after neighborhoods."
19001,15.02.2026 17:07,399000,https://www.bazaraki.com/adv/6053922_3-bedroom-apartment-for-sale/,"Own three fully renovated, income-producing one-bedroom apartments in the heart of Limassol — all under one ownership, all currently rented, and generating returns.\nA rare chance to step straight into a cash-flow positive, ready-to-go investment in one of Cyprus’s most dynamic cities.\n🏠 Property Highlights\nThree independent one-bedroom units — each with private balcony\nApprox. 110 m² total built area\nFully furnished and stylishly decorated\nModern kitchens, bathrooms, and appliances (washing machine, fridge, cooktop, etc.)\nEach unit separately metered — flexible management and tenant billing\nCurrently leased to reliable tenants — enjoy instant passive income or switch to short-term or corporate lets for higher yield.\n📍 Prime Location — Central Yet Peaceful\nNestled on a quiet residential street just off the city center, this address offers:\nWalkable access to shops, cafés, and daily conveniences\nNearby public transport routes\nFast connection to the business district and Limassol’s seafront\nAn appealing setting for professionals, couples, and long-stay tenants"
19285,15.02.2026 12:43,275000,https://www.bazaraki.com/adv/6069699_2-bedroom-apartment-for-sale/,"2 bedroom ground floor apartment in the centre of limassol, 2 minutes to the central park and 4 mins to the beach. Very quiet location. spacious separate kitchen, family bathroom and 2 double bedrooms. parquet flooring - currently rented with a 6.5% return\nfull title deeds. Tenancy ends March 2025"
19305,15.02.2026 14:09,195000,https://www.bazaraki.com/adv/6273456_1-bedroom-apartment-for-sale/,"✨ For Sale – Prime Location Studio in Molos Area ✨\nA fantastic investment opportunity!\nThis 36 sqm ground floor renovated studio is located in the highly sought-after Molos area, just steps away from the seafront and all essential amenities.\n🏡 Property Highlights:\n36 sqm studio in excellent condition\nPrime, central location\nFully furnished and equipped\nOlder building\nCurrently rented as Airbnb with high yield\nSteady occupancy\nIdeal for investors or as a holiday home\n💼 Investment Advantages:\nTurnkey rental property\nProven short-term rental income\nStrong demand area\nHigh appreciation potential\n📩 Contact us for viewings.\nF.Z"
20542,13.02.2026 23:15,480000,https://www.bazaraki.com/adv/5915417_2-bedroom-apartment-for-sale/,"• 2 Bedrooms\n• 2 W/C\n• Internal Area: 92 m²\n• Covered Veranda: 21 m²\n• Uncovered Veranda: 20 m²\n• Floor Level: 1st\n• Fully furnished and equipped\n• Underfloor heating\n• Top-brand A/C units with VRV system\n• Modern Italian kitchen cabinets and wardrobes\n• Decorated gypsum ceilings with built-in spotlights\n• Double-glazed windows\n• Security gated entrance door\n• Storage room\n• Covered parking\n• Landscaped garden\n• Common indoor pool & jacuzzi\n• Construction Year: 2019\nLocation Highlights:\n• Prime location in the sought-after Columbia area of Limassol\n• Excellent access to the city center, highway and coastline\n• Ideal for both personal use and long-term investment\n• Currently rented – great opportunity for investors"
20997,13.02.2026 20:28,280000,https://www.bazaraki.com/adv/6266028_2-bedroom-apartment-for-sale/,"Location\n• Prime coastal location just 100 meters from the seaside\n• Situated next to the iconic Trilogy development\n• Walking distance to supermarkets, cafés, bars, and pharmacies\n• Close to schools and everyday amenities\n• High-demand area for both short- and long-term rentals\n• Excellent lifestyle and investment setting\nProperty Description\n• Fully renovated apartment (October 2025)\n• Modern interior with quality finishes\n• Fully furnished and equipped\n• Turn-key condition — ready for living or renting\n• Ideal for investment with immediate rental return\nLayout and Comfort\n• Bright living room with seating area\n• Separate kitchen with appliances\n• Two bedrooms with built-in wardrobes\n• Fully renovated bathroom (walls & floors retiled)\n• New flooring throughout the apartment\n• Good natural light\nKey Features\n• 2 bedrooms\n• 1 bathroom\n• Internal area: 80 m²\n• 1st floor\n• Fully furnished\n• 4 new air-conditioning units\n• Fully equipped kitchen including washing machine\n• New solar tank system\n• New piping, doors, and windows\n• Private parking space\n• Title Deed available\nInvestment Potential\n• Currently rented\n• Tenancy secured until January 2027\n• Passive income from day one\n• Highly rentable seaside location\nno VAT"
21078,13.02.2026 17:49,360000,https://www.bazaraki.com/adv/6265765_1-bedroom-apartment-for-sale/,"Prime Investment Opportunity Near the Sea\nA rare chance to acquire a high-yield, fully operational investment property in one of the most desirable coastal locations. Combining lifestyle appeal with immediate rental returns, this apartment is an ideal choice for investors seeking stable income and long-term capital growth, as well as for buyers looking to secure a seaside residence for future personal use.\nArea\n• Total: 72 m²\n• Covered area: 64 m²\n• Open veranda: 8 m²\nProperty Features\n• 1 spacious bedroom\n• Bright living room\n• Separate fully equipped kitchen\n• 1 bathroom\n• 1st floor\n• Year built: 2019\n• Fully furnished with modern appliances and stylish décor\n• Move-in ready condition\nAmenities\n• Landscaped garden\n• Beautiful sea view\n• Covered parking + additional open parking space\nInfrastructure & Location\nEnjoy the unique advantage of living just steps from the coastline while remaining close to premium lifestyle facilities:\n• 1 minute walk to the sea\n• Nearby luxury hotels with SPA, fitness & wellness centers\n• 2 minutes — supermarket\n• 3 minutes — pharmacy\n• 4 minutes — beach / seafront promenade\n• 21 minutes — shopping mall\nInvestment Potential\n• Apartment rented until February 2027\n• Secure long-term tenancy in place\n• Rental income: €1,850 / month\n• Annual income: €22,000\n• ROI: 6%\n• No VAT\nTitle deed is available\nThis is a turnkey investment generating immediate cash flow from day one, with strong rental demand driven by its prime seaside location. A highly liquid asset equally suited for portfolio expansion or future private residence by the coast."

:

In [10]:
df = utils.add_city_disctrict_cols(df)
df.iloc[0].T

url               https://www.bazaraki.com/adv/5415213_4-bedroom-detached-house-to-rent/
title                                                   4-bedroom detached house to rent
price                                                                            1650.00
original_price                                                                       NaN
price_per_sqm                                                                        NaN
                                                   ...
posted_dt                                                            2024-12-11T20:57:00
delete_date                                                                   2025-01-20
Property Type                                                                        NaN
city                                                                             Larnaca
district                                                                      Dromolaxia
Name: 5415213, Length: 51, dtype: object

In [11]:
# remove invalid properties
df = utils.filter_in(df, "`Property area` > 10 and `Property area` < 300")

removing 46400/214683 rows

In [12]:
df.price_per_sqm = df.price / (df["Property area"]).round(2)

In [13]:
# selected_df = saledf[saledf.price < 5000]
# print(f"removed {len(saledf) - len(selected_df)} rows")
# df = selected_df

In [14]:
# selected_df = df.query("`Bedrooms` in ('3', '2', '1', 'Studio')")
# print(f"removed {len(df) - len(selected_df)} rows")
# df = selected_df

In [15]:
def stats(saledf, rentdf):
    salestatdf = saledf.query("Condition == 'Resale'").groupby(["city", "Bedrooms"]).price_per_sqm.describe()
    rentstatdf = rentdf.groupby(["city", "Bedrooms"]).price_per_sqm.describe()
    common_index = salestatdf.index.intersection(rentstatdf.index)
    apr = rentstatdf.loc[common_index] / salestatdf.loc[common_index] * 12 * 100
    return pd.concat([apr, rentstatdf, salestatdf], axis=1, keys=['apr', 'rent', 'sale']).sort_values(by=('apr', '50%'), ascending=False).dropna()
    
print("apparts")
display(stats(df.query("cat1 == 'Apartments, flats for sale'"), df.query("cat1 == 'Apartments, flats to rent'")))
print("houses")
display(stats(df.query("cat1 == 'Houses for sale'"), df.query("cat1 == 'Houses to rent'")))

apparts

                          apr  \
                        count
city      Bedrooms
Famagusta 4            800.00
Larnaca   6 and more  1200.00
          Studio      2071.70
Paphos    Studio      2774.03
Larnaca   1           2172.17
Famagusta Studio      3333.33
Larnaca   3           1186.67
          2           2334.82
Limassol  Studio     20608.70
Nicosia   Studio      9171.43
          3           2577.97
Limassol  1           8473.73
Larnaca   4            720.00
Nicosia   1          12046.65
Paphos    2           1971.36
Limassol  2           5133.60
Nicosia   2           4790.60
Paphos    3           2117.65
Nicosia   6 and more  1600.00
Paphos    1           2025.69
Limassol  4           2467.61
Famagusta 2            804.07
          1           1143.53
Nicosia   4           2964.00
Famagusta 3            629.70
Limassol  5           1480.00
          3           3647.19
Paphos    4           3120.00
Nicosia   5            480.00
Limassol  6 and more  1440.00

                            \
                      mean
city      Bedrooms
Famagusta 4          22.44
Larnaca   6 and more  2.02
          Studio      8.63
Paphos    Studio      7.99
Larnaca   1           7.15
Famagusta Studio      4.67
Larnaca   3           6.37
          2           6.51
Limassol  Studio      6.94
Nicosia   Studio     21.80
          3           6.06
Limassol  1           5.75
Larnaca   4           4.99
Nicosia   1           6.07
Paphos    2           6.63
Limassol  2           5.75
Nicosia   2           6.07
Paphos    3          11.52
Nicosia   6 and more 11.49
Paphos    1           6.29
Limassol  4           5.09
Famagusta 2           5.30
          1           5.42
Nicosia   4           8.72
Famagusta 3           5.53
Limassol  5           4.47
          3           4.86
Paphos    4           4.30
Nicosia   5           3.86
Limassol  6 and more 14.05

                              \
                         std
city      Bedrooms
Famagusta 4             6.74
Larnaca   6 and more    0.75
          Studio        5.98
Paphos    Studio        6.57
Larnaca   1             3.92
Famagusta Studio        0.66
Larnaca   3             3.90
          2            31.50
Limassol  Studio        7.24
Nicosia   Studio     1243.10
          3             4.98
Limassol  1            36.43
Larnaca   4             2.60
Nicosia   1             5.15
Paphos    2            49.19
Limassol  2            31.77
Nicosia   2             5.73
Paphos    3           236.55
Nicosia   6 and more   65.32
Paphos    1             6.59
Limassol  4             4.90
Famagusta 2             3.65
          1             8.00
Nicosia   4            92.49
Famagusta 3             5.25
Limassol  5             2.36
          3            15.62
Paphos    4             3.58
Nicosia   5             4.89
Limassol  6 and more   31.86

                              \
                         min
city      Bedrooms
Famagusta 4            37.08
Larnaca   6 and more    6.12
          Studio       15.24
Paphos    Studio        7.72
Larnaca   1             4.16
Famagusta Studio       19.71
Larnaca   3           265.66
          2           208.00
Limassol  Studio        8.24
Nicosia   Studio       11.07
          3          2228.57
Limassol  1             1.03
Larnaca   4             8.13
Nicosia   1           159.47
Paphos    2            16.60
Limassol  2             0.61
Nicosia   2             7.47
Paphos    3            51.20
Nicosia   6 and more    6.90
Paphos    1             9.52
Limassol  4             5.12
Famagusta 2             7.45
          1             0.03
Nicosia   4             3.32
Famagusta 3            15.24
Limassol  5             3.79
          3           149.02
Paphos    4             7.63
Nicosia   5             5.39
Limassol  6 and more    2.96

                            \
                       25%
city      Bedrooms
Famagusta 4          27.33
Larnaca   6 and more 11.24
          Studio      9.30
Paphos    Studio      9.12
Larnaca   1           8.09
Famagusta Studio      7.88
Larnaca   3           6.53
          2           6.84
Limassol  Studio      5.83
Nicosia   Studio      6.58
          3           6.02
Limassol  1           6.19
Larnaca   4           6.69
Nicosia   1           6.02
Paphos    2           6.26
Limassol  2           6.35
Nicosia   2           5.94
Paphos    3           5.83
Nicosia   6 and more  6.40
Paphos    1           6.38
Limassol  4           5.69
Famagusta 2           5.85
          1           5.83
Nicosia   4           5.50
Famagusta 3           5.55
Limassol  5           6.44
          3           5.65
Paphos    4           4.56
Nicosia   5           3.25
Limassol  6 and more  2.29

                            \
                       50%
city      Bedrooms
Famagusta 4          22.07
Larnaca   6 and more 11.28
          Studio      9.46
Paphos    Studio      7.88
Larnaca   1           7.47
Famagusta Studio      7.37
Larnaca   3           6.93
          2           6.89
Limassol  Studio      6.87
Nicosia   Studio      6.87
          3           6.12
Limassol  1           6.10
Larnaca   4           6.07
Nicosia   1           6.05
Paphos    2           6.03
Limassol  2           6.00
Nicosia   2           6.00
Paphos    3           5.98
Nicosia   6 and more  5.93
Paphos    1           5.91
Limassol  4           5.65
Famagusta 2           5.52
          1           5.50
Nicosia   4           5.48
Famagusta 3           5.45
Limassol  5           5.29
          3           5.07
Paphos    4           4.18
Nicosia   5           3.67
Limassol  6 and more  2.26

                            \
                       75%
city      Bedrooms
Famagusta 4          19.16
Larnaca   6 and more  2.52
          Studio      9.44
Paphos    Studio      7.94
Larnaca   1           7.11
Famagusta Studio      6.29
Larnaca   3           7.00
          2           6.36
Limassol  Studio      7.40
Nicosia   Studio      6.71
          3           6.14
Limassol  1           5.83
Larnaca   4           4.96
Nicosia   1           6.00
Paphos    2           6.16
Limassol  2           5.24
Nicosia   2           6.10
Paphos    3           6.38
Nicosia   6 and more 10.67
Paphos    1           6.22
Limassol  4           5.25
Famagusta 2           5.59
          1           4.53
Nicosia   4           5.39
Famagusta 3           5.93
Limassol  5           5.56
          3           4.51
Paphos    4           3.94
Nicosia   5           4.10
Limassol  6 and more 22.64

                              \
                         max
city      Bedrooms
Famagusta 4            17.11
Larnaca   6 and more    1.02
          Studio        7.49
Paphos    Studio        6.67
Larnaca   1             1.93
Famagusta Studio        1.00
Larnaca   3             2.47
          2           221.19
Limassol  Studio        9.93
Nicosia   Studio     4835.56
          3             4.13
Limassol  1           297.31
Larnaca   4             2.65
Nicosia   1             7.36
Paphos    2           216.24
Limassol  2           210.28
Nicosia   2             6.96
Paphos    3           508.50
Nicosia   6 and more   24.25
Paphos    1            12.50
Limassol  4             7.82
Famagusta 2             3.06
          1            17.28
Nicosia   4           233.44
Famagusta 3             3.78
Limassol  5             2.72
          3           139.99
Paphos    4             6.25
Nicosia   5             3.68
Limassol  6 and more   24.31

                         rent  \
                        count
city      Bedrooms
Famagusta 4              2.00
Larnaca   6 and more     5.00
          Studio       183.00
Paphos    Studio       178.00
Larnaca   1           1392.00
Famagusta Studio        50.00
Larnaca   3            979.00
          2           4370.00
Limassol  Studio       790.00
Nicosia   Studio       535.00
          3           3433.00
Limassol  1           4597.00
Larnaca   4             39.00
Nicosia   1           4648.00
Paphos    2           2180.00
Limassol  2          11649.00
Nicosia   2           7134.00
Paphos    3            690.00
Nicosia   6 and more     4.00
Paphos    1            920.00
Limassol  4            584.00
Famagusta 2            329.00
          1            162.00
Nicosia   4            247.00
Famagusta 3             53.00
Limassol  5             37.00
          3           6106.00
Paphos    4             26.00
Nicosia   5              4.00
Limassol  6 and more     6.00

                            \
                      mean
city      Bedrooms
Famagusta 4          41.25
Larnaca   6 and more 16.47
          Studio     16.80
Paphos    Studio     17.86
Larnaca   1          14.05
Famagusta Studio     15.80
Larnaca   3          11.83
          2          13.64
Limassol  Studio     25.94
Nicosia   Studio     44.14
          3           9.62
Limassol  1          25.79
Larnaca   4          11.63
Nicosia   1          11.74
Paphos    2          14.99
Limassol  2          24.49
Nicosia   2          10.42
Paphos    3          26.22
Nicosia   6 and more 10.84
Paphos    1          15.13
Limassol  4          32.19
Famagusta 2          10.68
          1          12.83
Nicosia   4          15.98
Famagusta 3          11.63
Limassol  5          32.92
          3          22.66
Paphos    4          12.00
Nicosia   5           4.97
Limassol  6 and more 81.52

                             \
                        std
city      Bedrooms
Famagusta 4            5.50
Larnaca   6 and more   9.10
          Studio       5.42
Paphos    Studio       6.86
Larnaca   1            4.66
Famagusta Studio       3.93
Larnaca   3            4.88
          2           37.92
Limassol  Studio       8.71
Nicosia   Studio     691.14
          3            3.64
Limassol  1           90.24
Larnaca   4            4.25
Nicosia   1            2.72
Paphos    2           38.61
Limassol  2           92.04
Nicosia   2            3.17
Paphos    3          335.62
Nicosia   6 and more  10.55
Paphos    1            5.34
Limassol  4           24.77
Famagusta 2            4.67
          1           12.83
Nicosia   4           99.58
Famagusta 3            8.84
Limassol  5           13.58
          3           54.75
Paphos    4            5.38
Nicosia   5            2.03
Limassol  6 and more 120.85

                            \
                       min
city      Bedrooms
Famagusta 4          37.36
Larnaca   6 and more  6.15
          Studio      8.14
Paphos    Studio      4.06
Larnaca   1           1.67
Famagusta Studio     10.00
Larnaca   3           2.07
          2           1.50
Limassol  Studio      2.33
Nicosia   Studio      3.60
          3           2.00
Limassol  1           1.33
Larnaca   4           5.36
Nicosia   1           1.38
Paphos    2           4.77
Limassol  2           0.67
Nicosia   2           1.50
Paphos    3           0.48
Nicosia   6 and more  5.36
Paphos    1           4.58
Limassol  4           5.93
Famagusta 2           4.03
          1           0.02
Nicosia   4           2.00
Famagusta 3           5.45
Limassol  5           8.00
          3           2.22
Paphos    4           6.43
Nicosia   5           3.00
Limassol  6 and more  8.00

                            \
                       25%
city      Bedrooms
Famagusta 4          39.30
Larnaca   6 and more 12.12
          Studio     13.28
Paphos    Studio     13.02
Larnaca   1          11.04
Famagusta Studio     12.96
Larnaca   3           8.49
          2          10.00
Limassol  Studio     20.00
Nicosia   Studio     11.11
          3           7.09
Limassol  1          19.35
Larnaca   4           8.26
Nicosia   1          10.00
Paphos    2          10.77
Limassol  2          16.67
Nicosia   2           8.44
Paphos    3           9.50
Nicosia   6 and more  5.54
Paphos    1          11.82
Limassol  4          15.59
Famagusta 2           8.12
          1           8.33
Nicosia   4           7.05
Famagusta 3           7.22
Limassol  5          19.44
          3          13.91
Paphos    4           8.45
Nicosia   5           3.38
Limassol  6 and more  8.60

                            \
                       50%
city      Bedrooms
Famagusta 4          41.25
Larnaca   6 and more 13.38
          Studio     15.96
Paphos    Studio     16.00
Larnaca   1          13.00
Famagusta Studio     14.48
Larnaca   3          10.83
          2          12.18
Limassol  Studio     25.00
Nicosia   Studio     13.37
          3           8.80
Limassol  1          23.33
Larnaca   4          11.36
Nicosia   1          11.46
Paphos    2          13.13
Limassol  2          20.00
Nicosia   2           9.79
Paphos    3          12.17
Nicosia   6 and more  5.66
Paphos    1          14.00
Limassol  4          23.48
Famagusta 2           9.56
          1          10.21
Nicosia   4           9.09
Famagusta 3           8.18
Limassol  5          34.67
          3          17.89
Paphos    4          11.18
Nicosia   5           4.88
Limassol  6 and more 11.55

                             \
                        75%
city      Bedrooms
Famagusta 4           43.19
Larnaca   6 and more  20.98
          Studio      19.67
Paphos    Studio      21.00
Larnaca   1           16.00
Famagusta Studio      17.83
Larnaca   3           13.64
          2           15.00
Limassol  Studio      31.08
Nicosia   Studio      16.26
          3           11.25
Limassol  1           27.78
Larnaca   4           14.95
Nicosia   1           13.00
Paphos    2           16.25
Limassol  2           24.44
Nicosia   2           11.63
Paphos    3           16.19
Nicosia   6 and more  10.95
Paphos    1           17.67
Limassol  4           40.00
Famagusta 2           11.54
          1           12.48
Nicosia   4           11.46
Famagusta 3           10.96
Limassol  5           44.78
          3           24.21
Paphos    4           13.04
Nicosia   5            6.47
Limassol  6 and more 115.67

                               \
                          max
city      Bedrooms
Famagusta 4             45.14
Larnaca   6 and more    29.72
          Studio        43.33
Paphos    Studio        44.48
Larnaca   1             48.15
Famagusta Studio        27.27
Larnaca   3             41.18
          2           2500.00
Limassol  Studio        70.00
Nicosia   Studio     16000.00
          3             44.44
Limassol  1           6112.90
Larnaca   4             22.07
Nicosia   1             46.15
Paphos    2           1801.98
Limassol  2           5961.54
Nicosia   2             53.49
Paphos    3           8828.12
Nicosia   6 and more    26.67
Paphos    1             83.33
Limassol  4            192.31
Famagusta 2             36.96
          1            144.00
Nicosia   4           1573.43
Famagusta 3             42.28
Limassol  5             60.00
          3           3492.65
Paphos    4             33.20
Nicosia   5              7.14
Limassol  6 and more   300.00

                        sale  \
                       count
city      Bedrooms
Famagusta 4             3.00
Larnaca   6 and more    5.00
          Studio      106.00
Paphos    Studio       77.00
Larnaca   1           769.00
Famagusta Studio       18.00
Larnaca   3           990.00
          2          2246.00
Limassol  Studio       46.00
Nicosia   Studio       70.00
          3          1598.00
Limassol  1           651.00
Larnaca   4            65.00
Nicosia   1           463.00
Paphos    2          1327.00
Limassol  2          2723.00
Nicosia   2          1787.00
Paphos    3           391.00
Nicosia   6 and more    3.00
Paphos    1           545.00
Limassol  4           284.00
Famagusta 2           491.00
          1           170.00
Nicosia   4           100.00
Famagusta 3           101.00
Limassol  5            30.00
          3          2009.00
Paphos    4            10.00
Nicosia   5            10.00
Limassol  6 and more    5.00

                              \
                        mean
city      Bedrooms
Famagusta 4          2205.99
Larnaca   6 and more 9805.14
          Studio     2336.72
Paphos    Studio     2680.67
Larnaca   1          2355.86
Famagusta Studio     4058.20
Larnaca   3          2226.57
          2          2515.98
Limassol  Studio     4484.45
Nicosia   Studio     2429.20
          3          1905.92
Limassol  1          5380.13
Larnaca   4          2799.35
Nicosia   1          2321.10
Paphos    2          2714.18
Limassol  2          5112.07
Nicosia   2          2059.01
Paphos    3          2730.19
Nicosia   6 and more 1131.91
Paphos    1          2886.07
Limassol  4          7587.94
Famagusta 2          2416.17
          1          2840.61
Nicosia   4          2199.49
Famagusta 3          2523.45
Limassol  5          8829.75
          3          5596.20
Paphos    4          3345.66
Nicosia   5          1546.84
Limassol  6 and more 6961.99

                               \
                          std
city      Bedrooms
Famagusta 4            979.45
Larnaca   6 and more 14633.90
          Studio      1087.52
Paphos    Studio      1253.36
Larnaca   1           1425.30
Famagusta Studio      7196.23
Larnaca   3           1501.42
          2           1444.48
Limassol  Studio      1444.05
Nicosia   Studio       667.18
          3            876.80
Limassol  1           2972.37
Larnaca   4           1959.40
Nicosia   1            633.73
Paphos    2            942.05
Limassol  2           3476.63
Nicosia   2            663.42
Paphos    3           1702.56
Nicosia   6 and more   193.91
Paphos    1            973.23
Limassol  4           6068.17
Famagusta 2           1536.16
          1           1924.32
Nicosia   4           1292.09
Famagusta 3           2020.91
Limassol  5           6900.76
          3           4206.38
Paphos    4           1800.19
Nicosia   5            498.78
Limassol  6 and more  4551.41

                              \
                         min
city      Bedrooms
Famagusta 4          1208.79
Larnaca   6 and more 1206.90
          Studio      641.03
Paphos    Studio      631.07
Larnaca   1           481.28
Famagusta Studio      608.97
Larnaca   3             9.35
          2             8.65
Limassol  Studio      340.00
Nicosia   Studio      390.07
          3             1.08
Limassol  1          1553.57
Larnaca   4           790.60
Nicosia   1            10.40
Paphos    2           344.83
Limassol  2          1318.68
Nicosia   2           240.96
Paphos    3            11.25
Nicosia   6 and more  932.20
Paphos    1           576.92
Limassol  4          1388.89
Famagusta 2           649.35
          1           612.24
Nicosia   4           722.22
Famagusta 3           429.45
Limassol  5          2536.23
          3            17.89
Paphos    4          1011.24
Nicosia   5           667.87
Limassol  6 and more 3238.10

                              \
                         25%
city      Bedrooms
Famagusta 4          1725.66
Larnaca   6 and more 1293.71
          Studio     1714.29
Paphos    Studio     1714.29
Larnaca   1          1636.36
Famagusta Studio     1973.68
Larnaca   3          1561.30
          2          1753.54
Limassol  Studio     4117.91
Nicosia   Studio     2026.70
          3          1415.22
Limassol  1          3750.00
Larnaca   4          1481.48
Nicosia   1          1994.44
Paphos    2          2063.49
Limassol  2          3150.00
Nicosia   2          1703.70
Paphos    3          1956.29
Nicosia   6 and more 1038.14
Paphos    1          2224.49
Limassol  4          3285.60
Famagusta 2          1666.67
          1          1714.81
Nicosia   4          1536.68
Famagusta 3          1562.50
Limassol  5          3622.86
          3          2954.55
Paphos    4          2225.44
Nicosia   5          1244.27
Limassol  6 and more 4500.00

                              \
                         50%
city      Bedrooms
Famagusta 4          2242.52
Larnaca   6 and more 1423.08
          Studio     2023.81
Paphos    Studio     2435.90
Larnaca   1          2089.55
Famagusta Studio     2358.33
Larnaca   3          1876.02
          2          2122.50
Limassol  Studio     4365.50
Nicosia   Studio     2335.68
          3          1723.70
Limassol  1          4591.84
Larnaca   4          2247.71

houses

                       apr  \
                     count
city      Bedrooms
Paphos    Studio   2400.00
Limassol  1        8238.46
Nicosia   Studio   3120.00
Larnaca   4         694.99
          5         475.74
          3         881.34
Paphos    1        2360.00
Limassol  2        3116.26
          7         400.00
Nicosia   2        1720.75
Larnaca   2        1138.83
Paphos    5         935.59
          6         285.71
Famagusta 4         344.26
Nicosia   4         728.00
          5         312.24
Limassol  5        1087.06
Larnaca   1        1671.43
Nicosia   3         967.42
Paphos    2        1338.54
Limassol  6         473.68
          4        1457.64
Paphos    4        1359.31
Limassol  3        2361.54
Paphos    3        1145.76
Nicosia   1        2500.00
Famagusta 2         572.84
          3         418.88
          5         203.57

                          \
                    mean
city      Bedrooms
Paphos    Studio   12.30
Limassol  1         8.89
Nicosia   Studio    8.37
Larnaca   4         6.15
          5         6.12
          3         5.92
Paphos    1         6.51
Limassol  2         5.81
          7         4.97
Nicosia   2         5.63
Larnaca   2         5.58
Paphos    5         5.07
          6         5.86
Famagusta 4         5.53
Nicosia   4         5.70
          5         6.16
Limassol  5         4.94
Larnaca   1         5.46
Nicosia   3         5.29
Paphos    2         5.69
Limassol  6         7.01
          4         5.05
Paphos    4         4.45
Limassol  3         5.02
Paphos    3         5.07
Nicosia   1         5.46
Famagusta 2         5.20
          3         4.83
          5         5.47

                          \
                     std
city      Bedrooms
Paphos    Studio    6.96
Limassol  1         6.55
Nicosia   Studio   10.87
Larnaca   4         3.54
          5         3.74
          3         4.47
Paphos    1         4.60
Limassol  2         4.25
          7         1.95
Nicosia   2         3.89
Larnaca   2         8.59
Paphos    5         4.08
          6         3.31
Famagusta 4         6.64
Nicosia   4         3.48
          5         6.58
Limassol  5         3.87
Larnaca   1         4.04
Nicosia   3         5.04
Paphos    2         6.10
Limassol  6        10.79
          4         2.52
Paphos    4         1.76
Limassol  3         4.91
Paphos    3         4.73
Nicosia   1         5.55
Famagusta 2         4.38
          3         6.40
          5         5.16

                            \
                       min
city      Bedrooms
Paphos    Studio     25.20
Limassol  1           0.05
Nicosia   Studio      7.50
Larnaca   4          12.62
          5          11.86
          3        1152.00
Paphos    1          26.67
Limassol  2           6.15
          7          10.63
Nicosia   2          27.41
Larnaca   2           5.57
Paphos    5           9.36
          6          13.71
Famagusta 4          11.73
Nicosia   4           6.45
          5          19.59
Limassol  5           7.64
Larnaca   1           8.72
Nicosia   3           9.12
Paphos    2           6.00
Limassol  6           7.95
          4           2.05
Paphos    4           3.29
Limassol  3         273.20
Paphos    3           1.46
Nicosia   1           6.59
Famagusta 2           4.80
          3         897.44
          5           9.59

                          \
                     25%
city      Bedrooms
Paphos    Studio   19.96
Limassol  1        12.35
Nicosia   Studio    6.30
Larnaca   4         6.64
          5         6.69
          3         6.29
Paphos    1         7.70
Limassol  2         6.45
          7         6.20
Nicosia   2         6.24
Larnaca   2         6.69
Paphos    5         5.98
          6         9.65
Famagusta 4         4.70
Nicosia   4         5.60
          5         5.58
Limassol  5         6.61
Larnaca   1         5.03
Nicosia   3         5.26
Paphos    2         5.58
Limassol  6         7.66
          4         5.62
Paphos    4         4.97
Limassol  3         5.42
Paphos    3         5.23
Nicosia   1         5.26
Famagusta 2         6.31
          3         4.63
          5         5.52

                          \
                     50%
city      Bedrooms
Paphos    Studio   12.59
Limassol  1         9.81
Nicosia   Studio    7.47
Larnaca   4         7.38
          5         6.47
          3         6.21
Paphos    1         6.11
Limassol  2         6.11
          7         6.10
Nicosia   2         6.06
Larnaca   2         5.91
Paphos    5         5.84
          6         5.82
Famagusta 4         5.79
Nicosia   4         5.77
          5         5.74
Limassol  5         5.53
Larnaca   1         5.44
Nicosia   3         5.44
Paphos    2         5.43
Limassol  6         5.40
          4         5.27
Paphos    4         5.25
Limassol  3         5.21
Paphos    3         5.20
Nicosia   1         5.10
Famagusta 2         4.99
          3         4.69
          5         4.30

                          \
                     75%
city      Bedrooms
Paphos    Studio    9.96
Limassol  1         8.82
Nicosia   Studio   10.08
Larnaca   4         7.45
          5         6.48
          3         6.25
Paphos    1         6.25
Limassol  2         5.52
          7         3.96
Nicosia   2         5.54
Larnaca   2         5.39
Paphos    5         4.78
          6         6.38
Famagusta 4         5.55
Nicosia   4         6.19
          5         6.10
Limassol  5         5.32
Larnaca   1         5.90
Nicosia   3         5.38
Paphos    2         5.67
Limassol  6         5.70
          4         4.80
Paphos    4         5.08
Limassol  3         5.07
Paphos    3         5.24
Nicosia   1         5.61
Famagusta 2         4.50
          3         4.74
          5         5.72

                          \
                     max
city      Bedrooms
Paphos    Studio   11.41
Limassol  1         8.57
Nicosia   Studio   10.80
Larnaca   4         2.28
          5         3.84
          3         4.84
Paphos    1         4.68
Limassol  2         4.53
          7         3.27
Nicosia   2         4.00
Larnaca   2        17.45
Paphos    5         4.94
          6         3.32
Famagusta 4         4.95
Nicosia   4         1.02
          5         4.41
Limassol  5         4.76
Larnaca   1         3.47
Nicosia   3         6.18
Paphos    2         5.80
Limassol  6        10.75
          4         1.17
Paphos    4         0.90
Limassol  3        14.74
Paphos    3         5.03
Nicosia   1         6.55
Famagusta 2         3.18
          3        12.79
          5         3.63

                      rent  \
                     count
city      Bedrooms
Paphos    Studio      6.00
Limassol  1         357.00
Nicosia   Studio     13.00
Larnaca   4         439.00
          5          67.00
          3         921.00
Paphos    1          59.00
Limassol  2        1166.00
          7           2.00
Nicosia   2         304.00
Larnaca   2         391.00
Paphos    5          92.00
          6           5.00
Famagusta 4          70.00
Nicosia   4         546.00
          5          51.00
Limassol  5         308.00
Larnaca   1          39.00
Nicosia   3         782.00
Paphos    2         657.00
Limassol  6          30.00
          4        1256.00
Paphos    4         529.00
Limassol  3        3070.00
Paphos    3        1352.00
Nicosia   1          75.00
Famagusta 2         116.00
          3         281.00
          5          19.00

                          \
                    mean
city      Bedrooms
Paphos    Studio    9.92
Limassol  1        14.38
Nicosia   Studio   11.19
Larnaca   4        13.04
          5        12.83
          3        11.54
Paphos    1        10.61
Limassol  2        15.36
          7        18.62
Nicosia   2         8.13
Larnaca   2        12.69
Paphos    5        21.46
          6        15.45
Famagusta 4        16.80
Nicosia   4         9.12
          5         9.99
Limassol  5        22.86
Larnaca   1        10.85
Nicosia   3         7.94
Paphos    2        12.25
Limassol  6        27.20
          4        17.80
Paphos    4        16.21
Limassol  3        15.25
Paphos    3        14.17
Nicosia   1         8.88
Famagusta 2        10.15
          3        12.90
          5        25.87

                          \
                     std
city      Bedrooms
Paphos    Studio    5.20
Limassol  1         6.63
Nicosia   Studio    4.81
Larnaca   4         5.66
          5         4.33
          3         5.71
Paphos    1         4.25
Limassol  2         6.19
          7         3.71
Nicosia   2         2.86
Larnaca   2        14.22
Paphos    5        11.71
          6         6.48
Famagusta 4        13.48
Nicosia   4         3.25
          5         4.06
Limassol  5        14.35
Larnaca   1         4.31
Nicosia   3         3.20
Paphos    2         5.13
Limassol  6        27.66
          4        10.95
Paphos    4         8.48
Limassol  3         9.47
Paphos    3         7.34
Nicosia   1         3.31
Famagusta 2         4.75
          3         9.04
          5        13.48

                          \
                     min
city      Bedrooms
Paphos    Studio    2.10
Limassol  1         0.01
Nicosia   Studio    5.00
Larnaca   4         4.35
          5         6.47
          3         3.00
Paphos    1         4.44
Limassol  2         0.02
          7        16.00
Nicosia   2         2.25
Larnaca   2         2.60
Paphos    5         5.20
          6        10.00
Famagusta 4         4.44
Nicosia   4         1.92
          5         5.65
Limassol  5         3.60
Larnaca   1         4.29
Nicosia   3         1.52
Paphos    2         2.00
Limassol  6         5.86
          4         0.96
Paphos    4         2.46
Limassol  3         2.91
Paphos    3         0.50
Nicosia   1         3.85
Famagusta 2         2.40
          3         2.69
          5        12.00

                          \
                     25%
city      Bedrooms
Paphos    Studio    8.39
Limassol  1        10.00
Nicosia   Studio    7.50
Larnaca   4         8.75
          5         9.13
          3         8.24
Paphos    1         7.53
Limassol  2        11.25
          7        17.31
Nicosia   2         6.15
Larnaca   2         8.65
Paphos    5        13.72
          6        10.53
Famagusta 4         8.39
Nicosia   4         6.80
          5         6.91
Limassol  5        14.00
Larnaca   1         7.50
Nicosia   3         6.08
Paphos    2         8.94
Limassol  6        15.00
          4        11.50
Paphos    4        10.00
Limassol  3        10.77
Paphos    3         9.63
Nicosia   1         6.67
Famagusta 2         7.48
          3         9.00
          5        14.89

                          \
                     50%
city      Bedrooms
Paphos    Studio    9.54
Limassol  1        13.33
Nicosia   Studio   11.11
Larnaca   4        12.00
          5        12.00
          3        10.34
Paphos    1         8.89
Limassol  2        14.55
          7        18.62
Nicosia   2         7.85
Larnaca   2        10.71
Paphos    5        19.64
          6        12.50
Famagusta 4        15.62
Nicosia   4         8.33
          5         8.93
Limassol  5        18.44
Larnaca   1        10.00
Nicosia   3         7.38
Paphos    2        11.30
Limassol  6        16.86
          4        14.55
Paphos    4        14.07
Limassol  3        13.40
Paphos    3        12.50
Nicosia   1         8.18
Famagusta 2         9.25
          3        11.54
          5        19.00

                          \
                     75%
city      Bedrooms
Paphos    Studio   11.62
Limassol  1        18.46
Nicosia   Studio   15.00
Larnaca   4        16.67
          5        15.95
          3        13.79
Paphos    1        12.50
Limassol  2        18.89
          7        19.93
Nicosia   2        10.00
Larnaca   2        14.14
Paphos    5        25.50
          6        19.20
Famagusta 4        20.00
Nicosia   4        10.98
          5        11.11
Limassol  5        29.47
Larnaca   1        13.31
Nicosia   3         9.17
Paphos    2        14.44
Limassol  6        27.44
          4        20.00
Paphos    4        20.00
Limassol  3        17.65
Paphos    3        16.67
Nicosia   1        10.91
Famagusta 2        11.82
          3        15.00
          5        36.04

                           \
                      max
city      Bedrooms
Paphos    Studio    18.00
Limassol  1         41.67
Nicosia   Studio    20.00
Larnaca   4         36.11
          5         26.79
          3        109.09
Paphos    1         21.43
Limassol  2         59.83
          7         21.25
Nicosia   2         20.00
Larnaca   2        200.00
Paphos    5         66.67
          6         25.00
Famagusta 4        100.00
Nicosia   4         22.73
          5         23.21
Limassol  5        142.05
Larnaca   1         20.00
Nicosia   3         41.67
Paphos    2         43.75
Limassol  6        141.67
          4        141.67
Paphos    4         60.87
Limassol  3        347.22
Paphos    3         75.00
Nicosia   1         21.82
Famagusta 2         40.00
          3        138.89
          5         57.50

                      sale  \
                     count
city      Bedrooms
Paphos    Studio      3.00
Limassol  1          52.00
Nicosia   Studio      5.00
Larnaca   4         758.00
          5         169.00
          3        1254.00
Paphos    1          30.00
Limassol  2         449.00
          7           6.00
Nicosia   2         212.00
Larnaca   2         412.00
Paphos    5         118.00
          6          21.00
Famagusta 4         244.00
Nicosia   4         900.00
          5         196.00
Limassol  5         340.00
Larnaca   1          28.00
Nicosia   3         970.00
Paphos    2         589.00
Limassol  6          76.00
          4        1034.00
Paphos    4         467.00
Limassol  3        1560.00
Paphos    3        1416.00
Nicosia   1          36.00
Famagusta 2         243.00
          3         805.00
          5         112.00

                            \
                      mean
city      Bedrooms
Paphos    Studio    967.32
Limassol  1        1941.43
Nicosia   Studio   1604.44
Larnaca   4        2544.42
          5        2517.28
          3        2341.95
Paphos    1        1956.66
Limassol  2        3173.26
          7        4500.64
Nicosia   2        1733.06
Larnaca   2        2730.35
Paphos    5        5080.78
          6        3164.34
Famagusta 4        3647.50
Nicosia   4        1919.33
          5        1947.26
Limassol  5        5551.37
Larnaca   1        2384.87
Nicosia   3        1801.83
Paphos    2        2584.52
Limassol  6        4657.64
          4        4233.54
Paphos    4        4375.35
Limassol  3        3643.44
Paphos    3        3352.73
Nicosia   1        1952.88
Famagusta 2        2342.28
          3        3202.81
          5        5680.11

                            \
                       std
city      Bedrooms
Paphos    Studio    897.85
Limassol  1        1214.55
Nicosia   Studio    530.43
Larnaca   4        1920.08
          5        1387.13
          3        1531.58
Paphos    1        1106.91
Limassol  2        1747.28
          7        2282.21
Nicosia   2         882.00
Larnaca   2        1985.73
Paphos    5        3446.96
          6        2349.27
Famagusta 4        2434.75
Nicosia   4        1120.17
          5         739.40
Limassol  5        4452.30
Larnaca   1        1279.50
Nicosia   3         760.17
Paphos    2        1009.60
Limassol  6        3076.19
          4        5218.11
Paphos    4        5768.30
Limassol  3        2315.11
Paphos    3        1861.38
Nicosia   1         715.79
Famagusta 2        1300.78
          3        1695.86
          5        3135.36

                            \
                       min
city      Bedrooms
Paphos    Studio    100.00
Limassol  1         265.49
Nicosia   Studio    800.00
Larnaca   4         413.33
          5         654.55
          3           3.12
Paphos    1         200.00
Limassol  2           3.90
          7        1806.02
Nicosia   2          98.52
Larnaca   2         560.00
Paphos    5         666.67
          6         875.00
Famagusta 4         454.55
Nicosia   4         357.14
          5         346.15
Limassol  5         565.22
Larnaca   1         589.52
Nicosia   3         200.00
Paphos    2         400.00
Limassol  6         884.62
          4         562.50
Paphos    4         897.59
Limassol  3          12.78
Paphos    3         409.09
Nicosia   1         700.00
Famagusta 2         600.00
          3           3.60
          5        1502.06

                            \
                       25%
city      Bedrooms
Paphos    Studio    504.55
Limassol  1         971.61
Nicosia   Studio   1428.57
Larnaca   4        1580.41
          5        1636.36
          3        1570.39
Paphos    1        1172.40
Limassol  2        2093.02
          7        3351.85
Nicosia   2        1183.14
Larnaca   2        1551.97
Paphos    5        2752.77
          6        1308.72
Famagusta 4        2140.41
Nicosia   4        1458.33
          5        1485.24
Limassol  5        2542.25
Larnaca   1        1789.57
Nicosia   3        1385.10
Paphos    2        1923.08
Limassol  6        2349.12
          4        2456.14
Paphos    4        2413.79
Limassol  3        2384.62
Paphos    3        2208.20
Nicosia   1        1521.62
Famagusta 2        1422.38
          3        2333.33
          5        3235.18

                            \
                       50%
city      Bedrooms
Paphos    Studio    909.09
Limassol  1        1630.68
Nicosia   Studio   1785.71
Larnaca   4        1952.03
          5        2227.27
          3        2000.00
Paphos    1        1744.84
Limassol  2        2857.14
          7        3663.16
Nicosia   2        1554.25
Larnaca   2        2174.09
Paphos    5        4035.08
          6        2578.12
Famagusta 4        3236.57
Nicosia   4        1733.67
          5        1867.36
Limassol  5        4000.00
Larnaca   1        2204.17
Nicosia   3        1627.09
Paphos    2        2500.00
Limassol  6        3747.92
          4        3310.51
Paphos    4        3216.22
Limassol  3        3087.61
Paphos    3        2886.92
Nicosia   1        1926.59
Famagusta 2        2222.22
          3        2954.55
          5        5298.25

                            \
                       75%
city      Bedrooms
Paphos    Studio   1400.97
Limassol  1        2511.36
Nicosia   Studio   1785.71
Larnaca   4        2685.27
          5        2954.55
          3        2646.21
Paphos    1        2401.79
Limassol  2        4105.26
          7        6035.91
Nicosia   2        2165.39
Larnaca   2        3146.94
Paphos    5        6400.38
          6        3613.64
Famagusta 4        4321.57
Nicosia   4        2129.63
          5        2185.19
Limassol  5        6644.07
Larnaca   1        2708.33
Nicosia   3        2045.87
Paphos    2        3057.85
Limassol  6        5777.78
          4        5000.00
Paphos    4        4722.22
Limassol  3        4173.35
Paphos    3        3813.56
Nicosia   1        2333.33
Famagusta 2        3150.26
          3        3800.00
          5        7564.23


                         max
city      Bedrooms
Paphos    Studio     1892.86
Limassol  1          5833.33
Nicosia   Studio     2222.22
Larnaca   4         19047.62
          5          8362.99
          3         27058.82
Paphos    1          5500.00
Limassol  2         15833.33
          7          7796.61
Nicosia   2          6000.00
Larnaca   2         13750.00
Paphos    5         16187.05
          6          9027.78
Famagusta 4         24264.71
Nicosia   4         26857.14
          5          6315.79
Limassol  5         35833.33
Larnaca   1          6923.08
Nicosia   3          8095.24
Paphos    2          9051.72
Limassol  6         15808.82
          4        144827.59
Paphos    4         81428.57
Limassol  3         28260.87
Paphos    3         17894.74
Nicosia   1          4000.00
Famagusta 2         15113.64
          3         13035.71
          5         19021.74

In [16]:
rentdf = df.query("cat1 == 'Apartments, flats for sale' and price_per_sqm < 6000")
px.histogram(rentdf, x="price_per_sqm", barmode='overlay', facet_col="city", color="Bedrooms", title="Apts for sale per city/bedrooms").show()

In [17]:
rentdf = df.query("cat1 == 'Apartments, flats for sale' and price < 1000000")
px.histogram(rentdf, x="price", barmode='overlay', facet_col="city", color="Bedrooms", title="Apts sale prices per city/bedrooms").show()

In [18]:
rentdf = df.query("cat1 == 'Apartments, flats to rent' and price < 3000")
px.histogram(rentdf, x="price", barmode='overlay', facet_col="city", color="Bedrooms", title="Apts rent prices per city/bedrooms").show()

In [19]:
df.sort_values("views", ascending=False)

,url,title,price,original_price,price_per_sqm,location,posted,reference_number,views,lat,lng,sold,cat0,cat1,Property area,Pets,Type,Parking,Plot area,Furnishing,...,Reference number,Condition,Square meter price,Minimum stay,Land type,Plot Type,Parcel number,Planning zone,Registration number,Share,Density,Coverage,Registration block,Area,Pick a point,posted_dt,delete_date,Property Type,city,district
ad_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
4025924,https://www.bazaraki.com/adv/4025924_1-bedroom-apartment-to-rent/,Studio apartment to rent,600.00,NaN,17.14,"Limassol, Trimiklini",18.11.2024 13:34,NaN,27310,34.85,32.91,False,Cyprus real estate to rent,"Apartments, flats to rent",35.00,Not allowed,Apartment,Covered,NaN,Fully Furnished,...,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,None,2024-11-18T13:34:00,NaN,NaN,Limassol,Trimiklini
1241192,https://www.bazaraki.com/adv/1241192_serviced-offices-for-rent/,Serviced offices in limassol,650.00,NaN,59.09,"Limassol, Limassol - Agia Zoni",05.12.2024 15:10,NaN,22598,34.69,33.04,False,Cyprus real estate to rent,Commercial property,11.00,None,Offices,None,NaN,None,...,None,None,€59 /,None,None,None,None,None,NaN,None,None,None,NaN,NaN,None,2024-12-05T15:10:00,NaN,NaN,Limassol,Limassol - Agia Zoni
4095853,https://www.bazaraki.com/adv/4095853_1-bedroom-detached-house-for-sale/,2-bedroom detached house fоr sаle,70000.00,NaN,1272.73,"Paphos, Filousa Kelokedaron",29.11.2024 18:41,NaN,18964,NaN,NaN,False,Cyprus real estate for sale,Houses for sale,55.00,None,Detached house,None,156.00,Fully Furnished,...,None,Resale,€1.273 /,None,None,None,None,None,NaN,None,None,None,NaN,NaN,None,2024-11-29T18:41:00,2025-01-02,NaN,Paphos,Filousa Kelokedaron
2291746,https://www.bazaraki.com/adv/2291746_2-preserved-houses-2-diateretees-oikies/,3-bedroom detached house fоr sаle,75000.00,80000.00,294.12,"Nicosia, Moni Kato",12.11.2024 07:25,NaN,18630,35.07,33.10,False,Cyprus real estate for sale,Houses for sale,255.00,None,Detached house,No,NaN,Unfurnished,...,None,Resale,€294 /,None,None,None,None,None,NaN,None,None,None,NaN,NaN,None,2024-11-12T07:25:00,NaN,NaN,Nicosia,Moni Kato
4256623,https://www.bazaraki.com/adv/4256623_2-bedroom-detached-house-to-rent/,2-bedroom detached house to rent,700.00,NaN,5.83,"Limassol, Kaminaria",02.12.2024 06:19,NaN,16077,NaN,NaN,False,Cyprus real estate to rent,Houses to rent,120.00,Not allowed,Detached house,No,NaN,Fully Furnished,...,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,None,2024-12-02T06:19:00,NaN,NaN,Limassol,Kaminaria
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6195349,https://www.bazaraki.com/adv/6195349_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,3800.00,NaN,45.24,"Limassol, Germasogeia Tourist Area",08.01.2026 08:44,NaN,0,NaN,NaN,False,Cyprus real estate to rent,"Apartments, flats to rent",84.00,None,Apartment,No,NaN,None,...,10050,None,None,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2026-01-08T08:44:00,NaN,None,Limassol,Germasogeia Tourist Area
5574861,https://www.bazaraki.com/adv/5574861_2-bedroom-apartment-for-sale/,2-bedroom apartment fоr sаle,230000.00,NaN,2738.10,"Larnaca, Aradippou - Agios Fanourios",Yesterday 20:20,NaN,0,NaN,NaN,False,Cyprus real estate for sale,"Apartments, flats for sale",84.00,None,Apartment,Covered,NaN,Unfurnished,...,12872,Under construction,€2.738 /,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2024-12-15T20:20:00,2025-06-04,NaN,Larnaca,Aradippou - Agios Fanourios
5741728,https://www.bazaraki.com/adv/5741728_3-bedroom-apartment-for-sale/,3-bedroom apartment fоr sаle,310000.00,NaN,1640.21,"Nicosia, Lakatameia - Agios Nikolaos",Yesterday 13:48,NaN,0,NaN,NaN,False,Cyprus real estate for sale,"Apartments, flats for sale",189.00,None,Apartment,Covered,NaN,Unfurnished,...,126365,Brand new,€1.640 /,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2025-04-14T13:48:00,2025-04-25,NaN,Nicosia,Lakatameia - Agios Nikolaos
5741721,https://www.bazaraki.com/adv/5741721_3-bedroom-villa-for-sale/,3-bedroom villa fоr sаle,700000.00,NaN,3954.80,"Paphos, Kissonerga",Yesterday 13:48,NaN,0,NaN,NaN,False,Cyprus real estate for sale,Houses for sale,177.00,None,Villa,Covered,NaN,Unfurnished,...,134735,Brand new,€3.955 /,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2025-04-14T13:48:00,2025-08-22,NaN,Paphos,Kissonerga
6307295,https://www.bazaraki.com/adv/6307295_3-bedroom-penthouse-for-sale/,3-bedroom penthouse for sale,1020000.00,NaN,8869.57,"Larnaca, Larnaka - Arch Makarios III",02:21,NaN,0,NaN,NaN,False,Cyprus real estate for sale,"Apartments, flats for sale",115.00,None,Penthouse,Covered,NaN,Appliances οnly,...,5503,Brand new,€8.870 /,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2026-02-25T02:21:42,NaN,None,Larnaca,Larnaka - Arch Makarios III

In [20]:
utils.add_city_disctrict_cols(df).\
    query("cat1 == 'Apartments, flats for sale' and price < 300000 and Condition == 'Resale' and city == 'Paphos' and `Property area` > 75").\
    sort_values(["price_per_sqm"])

,url,title,price,original_price,price_per_sqm,location,posted,reference_number,views,lat,lng,sold,cat0,cat1,Property area,Pets,Type,Parking,Plot area,Furnishing,...,Reference number,Condition,Square meter price,Minimum stay,Land type,Plot Type,Parcel number,Planning zone,Registration number,Share,Density,Coverage,Registration block,Area,Pick a point,posted_dt,delete_date,Property Type,city,district
ad_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
5795358,https://www.bazaraki.com/adv/5795358_3-bedroom-apartment-for-sale/,3-bedroom apartment fоr sаle,1350.00,NaN,11.25,"Paphos, Geroskipou",Yesterday 16:03,NaN,48,34.76,32.45,False,Cyprus real estate for sale,"Apartments, flats for sale",120.00,None,Apartment,Uncovered,NaN,Fully Furnished,...,6079,Resale,€11 /,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2025-05-12T16:03:00,2025-05-22,NaN,Paphos,Geroskipou
5691022,https://www.bazaraki.com/adv/5691022_2-bedroom-apartment-for-sale/,2-bedroom apartment fоr sаle,30000.00,NaN,344.83,"Paphos, Paphos - Agios Theodoros",09.03.2025 09:45,NaN,1426,34.77,32.42,False,Cyprus real estate for sale,"Apartments, flats for sale",87.00,None,Apartment,Uncovered,NaN,Semi-Furnished,...,None,Resale,€345 /,None,None,None,None,None,27867.00,None,None,None,1.00,NaN,NaN,2025-03-09T09:45:00,2025-04-05,NaN,Paphos,Paphos - Agios Theodoros
6097394,https://www.bazaraki.com/adv/6097394_2-bedroom-apartment-for-sale/,2-bedroom apartment fоr sаle,105000.00,NaN,567.57,"Paphos, Pegeia",Yesterday 19:39,NaN,55,34.88,32.38,False,Cyprus real estate for sale,"Apartments, flats for sale",185.00,None,Apartment,Covered,NaN,Unfurnished,...,None,Resale,€568 /,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2025-11-18T19:39:33,2025-12-04,None,Paphos,Pegeia
5737939,https://www.bazaraki.com/adv/5737939_studio-apartment-for-sale/,Studio apartment fоr sаle,65000.00,NaN,631.07,"Paphos, Pegeia",Yesterday 17:30,NaN,53,NaN,NaN,False,Cyprus real estate for sale,"Apartments, flats for sale",103.00,None,Apartment,Uncovered,NaN,Unfurnished,...,152188,Resale,€631 /,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2025-04-05T17:30:00,2025-04-10,NaN,Paphos,Pegeia
5629290,https://www.bazaraki.com/adv/5629290_3-bedroom-apartment-for-sale/,3-bedroom apartment fоr sаle,210000.00,NaN,798.48,"Paphos, Geroskipou",03.02.2025 08:33,NaN,17,NaN,NaN,False,Cyprus real estate for sale,"Apartments, flats for sale",263.00,None,Apartment,Covered,NaN,Unfurnished,...,NIS15956,Resale,€798 /,None,None,None,None,None,NaN,None,None,None,NaN,NaN,None,2025-02-03T08:33:00,2025-08-13,NaN,Paphos,Geroskipou
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6152228,https://www.bazaraki.com/adv/6152228_2-bedroom-apartment-for-sale/,2-bedroom apartment for sale,280000.00,NaN,3684.21,"Paphos, Geroskipou",Yesterday 22:01,NaN,5,NaN,NaN,False,Cyprus real estate for sale,"Apartments, flats for sale",76.00,None,Apartment,No,NaN,Unfurnished,...,4418,Resale,€3.684 /,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2025-12-12T22:01:21,2026-01-28,None,Paphos,Geroskipou
6184597,https://www.bazaraki.com/adv/6184597_2-bedroom-apartment-for-sale/,2-bedroom apartment for sale,295000.00,NaN,3687.50,"Paphos, Paphos - Universal",29.12.2025 09:21,NaN,36,NaN,NaN,False,Cyprus real estate for sale,"Apartments, flats for sale",80.00,None,Apartment,Uncovered,NaN,Fully Furnished,...,None,Resale,€3.688 /,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2025-12-29T09:21:00,2026-01-22,None,Paphos,Paphos - Universal
6236196,https://www.bazaraki.com/adv/6236196_1-bedroom-apartment-for-sale/,1-bedroom apartment for sale,299000.00,NaN,3784.81,"Paphos, Paphos - Universal",Yesterday 11:57,NaN,12,NaN,NaN,False,Cyprus real estate for sale,"Apartments, flats for sale",79.00,None,Apartment,None,NaN,Unfurnished,...,None,Resale,€3.785 /,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2026-02-03T11:57:37,NaN,None,Paphos,Paphos - Universal
5833860,https://www.bazaraki.com/adv/5833860_2-bedroom-apartment-for-sale/,2-bedroom apartment fоr sаle,290000.00,NaN,3815.79,"Paphos, Tala",Yesterday 21:41,NaN,2,34.83,32.43,False,Cyprus real estate for sale,"Apartments, flats for sale",76.00,None,Apartment,Covered,NaN,None,...,19152,Resale,€3.816 /,None,None,None,None,None,NaN,None,None,None,NaN,NaN,NaN,2025-06-03T21:41:01,2025-09-04,NaN,Paphos,Tala
6000637,https://www.bazaraki.com/adv/6000637_2-bedroom-apartment-for-sale/,2-bedroom apartment fоr sаle,299000.00,NaN,3833.33,"Paphos, Paphos - Universal",29.09.2025 11:16,NaN,27,34.76,32.43,False,Cyprus real estate for sale,"Apartments, flats for sale",78.00,None,Apartment,Uncovered,NaN,Fully Furnished,...,None,Resale,€3.833 /,None,None,None,None,None,12208.00,None,None,None,NaN,NaN,NaN,2025-09-29T11:16:00,NaN,NaN,Paphos,Paphos - Universal

In [21]:
df = pd.read_parquet("/Users/alekseygrachev/git/bazaraki/output/2026-01-25 00:42:35 real-estate-to-rent_real-estate-for-sale.parquet")
df

,url,title,price,original_price,price_per_sqm,location,posted,ad_id,reference_number,views,lat,lng,sold,posted_dt,cat0,cat1,Property area,Pets,Type,Floor,...,Bathrooms,images,description,Construction year,Reference number,Plot area,Square meter price,Minimum stay,Share,Land type,Plot Type,Area,Condition,Density,Planning zone,Parcel number,Registration block,Registration number,Coverage,Property Type
0,https://www.bazaraki.com/adv/6176389_3-bedroom-penthouse-to-rent/,3-bedroom penthouse to rent,1900,NaN,NaN,"Nicosia, Agioi Omologites",23.01.2026 14:07,6176389,NaN,122,NaN,NaN,False,2026-01-23T14:07:00,Cyprus real estate to rent,"Apartments, flats to rent",150.00,Not allowed,Penthouse,4th,...,2,"[https://cdn1.bazaraki.com/media/cache1/bb/e2/bbe2881a75fed27f000842de8e821622.webp, https://cdn...",For rent renovated very attractive penthouse apartment with three bedrooms and large verandas. B...,None,None,NaN,None,None,None,None,None,NaN,None,None,None,None,NaN,NaN,None,None
1,https://www.bazaraki.com/adv/6219316_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,1300,NaN,NaN,"Limassol, Limassol - Omonia",22.01.2026 22:10,6219316,NaN,62,NaN,NaN,False,2026-01-22T22:10:00,Cyprus real estate to rent,"Apartments, flats to rent",103.00,Allowed,Apartment,1st,...,2,"[https://cdn1.bazaraki.com/media/cache1/7e/20/7e203e8fcefdcaefae8c2f43b627e8a9.webp, https://cdn...",Spacious Two Bedroom Apartment in Omonoia area.\nA very well‑maintained apartment in a highly co...,2015,None,NaN,None,None,None,None,None,NaN,None,None,None,None,NaN,NaN,None,None
2,https://www.bazaraki.com/adv/6219331_3-bedroom-penthouse-to-rent/,3-bedroom penthouse to rent,2450,NaN,NaN,"Limassol, Parekklisia Tourist Area",22.01.2026 22:38,6219331,NaN,45,NaN,NaN,False,2026-01-22T22:38:00,Cyprus real estate to rent,"Apartments, flats to rent",130.00,Not allowed,Penthouse,2nd,...,2,"[https://cdn1.bazaraki.com/media/cache1/56/17/5617fd2038e0805d4a7825140c7577a5.webp, https://cdn...","3 Bedroom flat fully furnished Available for rent with common pool and garden , private gate, 10...",2015,None,NaN,None,None,None,None,None,NaN,None,None,None,None,NaN,NaN,None,None
3,https://www.bazaraki.com/adv/6031486_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,2150,2500.00,NaN,"Larnaca, Livadia Larnakas",23.01.2026 20:26,6031486,NaN,85,NaN,NaN,False,2026-01-23T20:26:00,Cyprus real estate to rent,"Apartments, flats to rent",85.00,Allowed,Apartment,Ground floor,...,2,"[https://cdn1.bazaraki.com/media/cache1/46/e6/46e6636ce6bab6d2dd91e3f68276571c.webp, https://cdn...","For Rent – Luxury 2-Bedroom Ground Floor in Livadia, Larnaca\nExperience modern living at its fi...",2025,None,NaN,None,None,None,None,None,NaN,None,None,None,None,NaN,NaN,None,None
4,https://www.bazaraki.com/adv/6208931_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,700,NaN,NaN,"Nicosia, Egkomi",22.01.2026 22:44,6208931,NaN,79,NaN,NaN,False,2026-01-22T22:44:00,Cyprus real estate to rent,"Apartments, flats to rent",76.00,Not allowed,Apartment,1st,...,1,"[https://cdn1.bazaraki.com/media/cache1/11/97/1197271fca7257478ce723874104d5b8.webp, https://cdn...","Spacious FURNISHED 2 Bedrooms aapartment -Egkomi,Nicosia: (for long term rental)\n**LOCATION IT...",2000,None,NaN,None,None,None,None,None,NaN,None,None,None,None,NaN,NaN,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39200,https://www.bazaraki.com/adv/6220962_enoikiazetai-grapheio-agia-zone-lemesos/,Γραφειο αγία ζώνη λεμεσος,800,NaN,23.00,"Limassol, Limassol - Agia Zoni",Yesterday 14:43,6220962,NaN,93,NaN,NaN,False,2026-01-24T14:43:33,Cyprus real estate to rent,Commercial property,35.00,None,Offices,None,...,None,"[https://cdn1.bazaraki.com/media/cache1/c5/8e/c58ea6394dc2edc05c9e97409a5b4ddc.webp, https://cdn...","Διαθέσιμο γραφείο προς ενοικίαση καταλληλο για ψυχολόγο, επαγγελματια υγείας ή άλλη ειδικότητα.\...",2013,None,NaN,€23 /,None,None,None,None,NaN,None,None,None,None,NaN,NaN,None,None
39201,https://www.bazaraki.com/adv/6221288_1-bedroom-apartment-to-rent/,1-bedroom apartment to rent,700,NaN,NaN,"Nicosia, Strovolos - Stavros",Yesterday 13:12,6221288,NaN,72,NaN,NaN,False,2026-01-24T13:12:33,Cyprus real estate to rent,"Apartments, flats to rent",55.00,Not allowed,Apartment,1st,...,1,"[https://cdn1.bazaraki.com/media/cache1/25/79/25799d1b157f2cac8e0df2be056fc74d.webp, https://cdn...",One bedroom apartment for rent in Strovolos Stavrou area close to all amenities. Small building ...,2010,None,NaN,None,None,None,None,None,NaN,None,None,None,None,NaN,NaN,None,None
39202,https://www.bazaraki.com/adv/4424521_3-bedroom-detached-house-to-rent/,3-bedroom villa to rent,9500,NaN,NaN,"Paphos, Aphrodite hills Kouklia",Yesterday 19:36,4424521,NaN,8,NaN,NaN,False,2026-01-24T19:36:33,Cyprus real estate to rent,Houses to rent,205.00,Not allowed,Villa,None,...,3,"[https://cdn1.bazaraki.com/media/cache1/93/fe/93fecc3b6d974f5e4f5fe49b6953fa4a.webp, https://cdn...",*****HEATED SWIMMING POOL*****\n*****BIG BBQ AREA COVERED*****\n*****DAILY CLEANING INCLUDED****...,2018,None,NaN,None,None,None,None,None,NaN,None,None,None,None,NaN,NaN,None,None
39203,https://www.bazaraki.com/adv/6213519_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,1500,NaN,NaN,"Larnaca, Larnaka - Agios Nikolaos",Yesterday 20:06,6213519,NaN,164,NaN,NaN,False,2026-01-24T20:06:33,Cyprus real estate to rent,"Apartments, flats to rent",105.00,Allowed,Apartment,1st,...,2,"[https://cdn1.bazaraki.com/media/cache1/32/64/3264b642736fdfe50232df7b51695903.webp, https://cdn...",For Rent | Luxury 2-Bedroom Apartment – Faneromeni Area\nA stylish and fully furnished 2bedroom ...,2021,None,NaN,None,None,None,None,None,NaN,None,None,None,None,NaN,NaN,None,None
39204,https://www.bazaraki.com/adv/6220689_1-bedroom-apartment-to-rent/,1-bedroom apartment to rent,1200,NaN,NaN,"Limassol, Limassol - Omonia",23.01.2026 20:58,6220689,NaN,180,NaN,NaN,False,2026-01-23T20:58:00,Cyprus real estate to rent,"Apartments, flats to rent",62.00,Allowed,Apartment,1st,...,1,"[https://cdn1.bazaraki.com/media/cache1/98/ef/98efce4367daade4242c3ef47c423006.webp, https://cdn...","No agents!\nA one- bedroom apartment, fully furnished, AC unit, Smart TV , electrical appliance...",2025,None,NaN,None,None,None,None,None,NaN,None,None,None,None,NaN,NaN,None,None

In [22]:
df.price_per_sqm = df.price / (df["Property area"]).round(2)
df = utils.add_city_disctrict_cols(df).\
    query("cat1 == 'Apartments, flats for sale' and price_per_sqm < 20000 and Bedrooms in ('4', '3', '2', '1', 'Studio')").\
    sort_values(["Bedrooms", "Condition"])
df

,url,title,price,original_price,price_per_sqm,location,posted,ad_id,reference_number,views,lat,lng,sold,posted_dt,cat0,cat1,Property area,Pets,Type,Floor,...,description,Construction year,Reference number,Plot area,Square meter price,Minimum stay,Share,Land type,Plot Type,Area,Condition,Density,Planning zone,Parcel number,Registration block,Registration number,Coverage,Property Type,city,district
8149,https://www.bazaraki.com/adv/5056693_1-bedroom-apartment-for-sale/,1-bedroom apartment for sale,155000,NaN,2279.41,"Nicosia, Lakatameia - Agios Nikolaos",07.01.2026 12:14,5056693,NaN,554,NaN,NaN,False,2026-01-07T12:14:00,Cyprus real estate for sale,"Apartments, flats for sale",68.00,None,Apartment,3rd,...,"Welcome to HHP residences.\nOne bedroom Apartment, Modern Design, Part of a Megaproject\nOne bed...",2025,04,NaN,€2.279 /,None,None,None,None,NaN,Brand new,None,None,None,NaN,NaN,None,None,Nicosia,Lakatameia - Agios Nikolaos
8196,https://www.bazaraki.com/adv/6148574_1-bedroom-apartment-for-sale/,1-bedroom apartment for sale,255000,NaN,4112.90,"Limassol, Limassol - Mesa Geitonia",19.01.2026 15:35,6148574,NaN,64,NaN,NaN,False,2026-01-19T15:35:00,Cyprus real estate for sale,"Apartments, flats for sale",62.00,None,Apartment,1st,...,Apartment 201 - NOA Residences\nFloor: 1\nType: Apartment\nCity: Limassol\nArea: Mesa Geitonia\n...,None,NOA201,NaN,€4.113 /,None,None,None,None,NaN,Brand new,None,None,None,NaN,NaN,None,None,Limassol,Limassol - Mesa Geitonia
8209,https://www.bazaraki.com/adv/5953866_1-bedroom-apartment-for-sale/,1-bedroom apartment for sale,319000,NaN,4557.14,"Limassol, Historical Center",19.01.2026 16:14,5953866,NaN,63,NaN,NaN,False,2026-01-19T16:14:00,Cyprus real estate for sale,"Apartments, flats for sale",70.00,None,Apartment,2nd,...,"1-Bedroom Apartment 103 – THE COLLECTION Residences, Limassol Historical Centre\nModern Design. ...",None,COLLECTION103,NaN,€4.557 /,None,None,None,None,NaN,Brand new,None,None,None,NaN,NaN,None,None,Limassol,Historical Center
8535,https://www.bazaraki.com/adv/5070660_1-bedroom-apartment-for-sale/,1-bedroom apartment for sale,385000,NaN,5833.33,"Limassol, Potamos Germasogeias",20.01.2026 13:11,5070660,NaN,591,NaN,NaN,False,2026-01-20T13:11:00,Cyprus real estate for sale,"Apartments, flats for sale",66.00,None,Apartment,2nd,...,Be the first to experience life in our new residential complex under construction!\nExcellent Lo...,2025,None,NaN,€5.833 /,None,None,None,None,NaN,Brand new,None,None,None,NaN,NaN,None,None,Limassol,Potamos Germasogeias
8556,https://www.bazaraki.com/adv/5868357_1-bedroom-apartment-for-sale/,1-bedroom apartment for sale,155000,NaN,3100.00,"Nicosia, Strovolos - Stavros",21.01.2026 07:25,5868357,NaN,572,NaN,NaN,False,2026-01-21T07:25:00,Cyprus real estate for sale,"Apartments, flats for sale",50.00,None,Apartment,1st,...,1-BEDROOM APARTMENT\nDELIVERY IN 5 MONTHS\n📍Strovolos – In a cul-de-sac and facing impressive gr...,2025,None,NaN,€3.100 /,None,None,None,None,NaN,Brand new,None,None,None,NaN,NaN,None,None,Nicosia,Strovolos - Stavros
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37394,https://www.bazaraki.com/adv/6028332_studio-apartment-for-sale/,Studio apartment for sale,231000,254000.00,7965.52,"Limassol, Historical Center",02.01.2026 17:09,6028332,NaN,33,NaN,NaN,False,2026-01-02T17:09:00,Cyprus real estate for sale,"Apartments, flats for sale",29.00,None,Apartment,1st,...,"For sale: A modern studio apartment currently under construction, located in the heart of the Hi...",None,6655,NaN,€7.966 /,None,None,None,None,NaN,Under construction,None,None,None,NaN,NaN,None,None,Limassol,Historical Center
37663,https://www.bazaraki.com/adv/5798647_studio-apartment-for-sale/,Studio apartment for sale,135000,NaN,3214.29,"Larnaca, Larnaka - Sotiros",02.01.2026 05:15,5798647,NaN,36,NaN,NaN,False,2026-01-02T05:15:00,Cyprus real estate for sale,"Apartments, flats for sale",42.00,None,Apartment,2nd,...,"Second Floor Studio Apartment for sale in McDonalds Drive Thru area, Larnaca. Very close to the ...",None,51599,NaN,€3.214 /,None,None,None,None,NaN,Under construction,None,None,None,NaN,NaN,None,None,Larnaca,Larnaka - Sotiros
37963,https://www.bazaraki.com/adv/5319989_studio-apartment-for-sale/,Studio apartment for sale,275000,NaN,7051.28,"Limassol, Potamos Germasogeias",01.01.2026 20:35,5319989,NaN,29,NaN,NaN,False,2026-01-01T20:35:00,Cyprus real estate for sale,"Apartments, flats for sale",39.00,None,Apartment,1st,...,"Luxury studio for sale in Germasogeia area, Limassol\nA new high-quality apartment block located...",None,53071,NaN,€7.051 /,None,None,None,None,NaN,Under construction,None,None,None,NaN,NaN,None,None,Limassol,Potamos Germasogeias
37985,https://www.bazaraki.com/adv/6127426_studio-apartment-for-sale/,Studio apartment for sale,165000,NaN,4125.00,"Paphos, Geroskipou",01.01.2026 20:35,6127426,NaN,62,NaN,NaN,False,2026-01-01T20:35:00,Cyprus real estate for sale,"Apartments, flats for sale",40.00,None,Apartment,2nd,...,"For sale: Off-plan, modern studio apartment situated on the second floor of a stylish three-stor...",None,57185,NaN,€4.125 /,None,None,None,None,NaN,Under construction,None,None,None,NaN,NaN,None,None,Paphos,Geroskipou
38080,https://www.bazaraki.com/adv/5538307_studio-apartment-for-sale/,Studio apartment for sale,250000,NaN,7142.86,"Limassol, Limassol - Zakaki",01.01.2026 20:20,5538307,NaN,21,NaN,NaN,False,2026-01-01T20:20:00,Cyprus real estate for sale,"Apartments, flats for sale",35.00,None,Apartment,1st,...,Incredible studio apartment is available for sale in the Zakaki area.\nThe studio apartment will...,None,SR20336,NaN,€7.143 /,None,None,None,None,NaN,Under construction,None,None,None,NaN,NaN,None,None,Limassol,Limassol - Zakaki

In [23]:
px.box(df, x=df["Bedrooms"] + "|" + df["Condition"], y="price_per_sqm", title="Prices per bedroom/condition", facet_col="city", height=1600)

In [24]:
df = utils.read_df("output/2026-01-13 00:34:06 real-estate-to-rent_real-estate-for-sale.parquet")
df

,url,title,price,original_price,price_per_sqm,location,posted,ad_id,reference_number,views,lat,lng,sold,posted_dt,cat0,cat1,Reference number,Property area,Type,Included,...,Furnishing,Postal code,Bedrooms,Bathrooms,Air conditioning,Construction year,Plot area,Minimum stay,Share,Land type,Plot Type,Area,Condition,Density,Coverage,Parcel number,Planning zone,Registration block,Registration number,Property Type
0,https://www.bazaraki.com/adv/6046095_office-in-neapolis/,Office in neapolis,2500,NaN,23.00,"Limassol, Limassol - Neapolis",Yesterday 02:20,6046095,NaN,3,NaN,NaN,False,2026-01-12T02:20:04,Cyprus real estate to rent,Commercial property,14654,110.00,Offices,Elevator,...,None,NaN,None,None,None,None,NaN,None,None,None,None,NaN,None,None,None,None,None,NaN,NaN,None
1,https://www.bazaraki.com/adv/6082268_3-bedroom-apartment-to-rent/,3-bedroom apartment to rent,920,NaN,NaN,"Nicosia, Nicosia - Lykabittos",Yesterday 09:03,6082268,NaN,279,NaN,NaN,False,2026-01-12T09:03:04,Cyprus real estate to rent,"Apartments, flats to rent",None,130.00,Apartment,"Elevator, Balcony",...,Semi-Furnished,1071.00,3,1,None,None,NaN,None,None,None,None,NaN,None,None,None,None,None,NaN,NaN,None
2,https://www.bazaraki.com/adv/6122552_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,1000,1100.00,NaN,"Nicosia, Strovolos - Agios Vasileios",Yesterday 10:07,6122552,NaN,104,NaN,NaN,False,2026-01-12T10:07:04,Cyprus real estate to rent,"Apartments, flats to rent",None,88.00,Apartment,"Elevator, Balcony, Storage room",...,Appliances οnly,NaN,2,1,"Full, all rooms",2017,NaN,None,None,None,None,NaN,None,None,None,None,None,NaN,NaN,None
3,https://www.bazaraki.com/adv/6200884_4-bedroom-semi-detached-to-rent/,4-bedroom semi-detached to rent,2200,NaN,NaN,"Nicosia, Strovolos - Acropolis",Yesterday 08:54,6200884,NaN,9,NaN,NaN,False,2026-01-12T08:54:04,Cyprus real estate to rent,Houses to rent,None,160.00,Semi-detached,"Alarm, Fireplace, Balcony",...,Fully Furnished,NaN,4,3,"Full, all rooms",None,NaN,None,None,None,None,NaN,None,None,None,None,None,NaN,NaN,None
4,https://www.bazaraki.com/adv/6027548_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,1200,NaN,NaN,"Larnaca, Larnaka - Sotiros",Yesterday 11:34,6027548,NaN,227,NaN,NaN,False,2026-01-12T11:34:04,Cyprus real estate to rent,"Apartments, flats to rent",None,80.00,Apartment,"Pool, Elevator, Balcony, Storage room",...,Fully Furnished,NaN,2,2,"Full, all rooms",2025,NaN,None,None,None,None,NaN,None,None,None,None,None,NaN,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38854,https://www.bazaraki.com/adv/6196834_3-bedroom-apartment-to-rent/,3-bedroom apartment to rent,1900,NaN,NaN,"Limassol, Agios Athanasios",Yesterday 19:29,6196834,NaN,36,NaN,NaN,False,2026-01-12T19:29:04,Cyprus real estate to rent,"Apartments, flats to rent",None,110.00,Apartment,"Elevator, Balcony, Storage room",...,Fully Furnished,NaN,3,None,None,2024,NaN,None,None,None,None,NaN,None,None,None,None,None,NaN,NaN,None
38855,https://www.bazaraki.com/adv/6004677_4-bedroom-villa-to-rent/,4-bedroom villa to rent,15000,17000.00,NaN,"Limassol, Agios Tychon Tourist Area",Yesterday 20:40,6004677,NaN,449,NaN,NaN,False,2026-01-12T20:40:04,Cyprus real estate to rent,Houses to rent,None,350.00,Villa,"Pool, Garden, Elevator, Alarm, Balcony, Storage room",...,Fully Furnished,NaN,4,4,"Full, all rooms",2022,150.00,None,None,None,None,NaN,None,None,None,None,None,NaN,NaN,None
38856,https://www.bazaraki.com/adv/6196804_2-bedroom-apartment-to-rent/,2-bedroom apartment to rent,1480,NaN,NaN,"Limassol, Limassol - Tsirion",Yesterday 19:29,6196804,NaN,45,NaN,NaN,False,2026-01-12T19:29:04,Cyprus real estate to rent,"Apartments, flats to rent",None,95.00,Apartment,"Elevator, Balcony",...,Fully Furnished,NaN,2,1,None,None,NaN,None,None,None,None,NaN,None,None,None,None,None,NaN,NaN,None
38857,https://www.bazaraki.com/adv/6202259_1-bedroom-apartment-to-rent/,1-bedroom apartment to rent,1300,NaN,NaN,"Limassol, Limassol - Zakaki",Yesterday 22:16,6202259,NaN,53,NaN,NaN,False,2026-01-12T22:16:04,Cyprus real estate to rent,"Apartments, flats to rent",None,70.00,Apartment,"Elevator, Balcony, Storage room",...,Fully Furnished,3046.00,1,1,"Full, all rooms",2025,NaN,None,None,None,None,NaN,None,None,None,None,None,NaN,NaN,None
38858,https://www.bazaraki.com/adv/6171413_studio-apartment-to-rent/,Studio apartment to rent,1300,NaN,NaN,"Limassol, Historical Center",Yesterday 23:15,6171413,NaN,41,NaN,NaN,False,2026-01-12T23:15:04,Cyprus real estate to rent,"Apartments, flats to rent",None,40.00,Apartment,"Garden, Elevator, Alarm, Balcony, Playroom, Attic/Loft",...,Fully Furnished,NaN,Studio,1,"Full, all rooms",2025,NaN,None,None,None,None,NaN,None,None,None,None,None,NaN,NaN,None

In [25]:
# dont limit pandas columns output
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 100)
pd.set_option('display.max_rows', 100)

In [26]:
results = []
for file_name in sorted(glob("output/2025-*.parquet")):
    print(f"Reading {file_name}")
    result = parse("output/{date} {time} {postfix}", file_name)
    if result is None:
        print(f"Failed to parse {file_name}")
        continue
    if result["postfix"].startswith("fast"):
        print(f"Skipping fast run")
        continue
    df = utils.read_df(file_name)
    
    # display(df.query("description.str.contains('Closed gated complex with pool barbecue and green area')", engine='python'))
    # display(df.query("description.str.contains('3rd floor of 5 story beach front building')", engine='python'))
    found = df.query("description.str.contains('Opposite Four Seasons Hotel') and cat1.str.contains('rent')", engine='python')
    if not found.empty:
        display(found)

Reading output/2025-01-02 12:05:37 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-01-09 16:40:56 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-01-11 16:28:55 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-01-13 19:44:12 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-01-14 17:35:36 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-01-16 22:17:14 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-01-20 18:35:48 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-01-29 12:26:50 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-01-30 20:47:55 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-02-04 21:11:22 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-02-05 18:32:44 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-02-10 14:44:23 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-02-22 13:10:31 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-03-22 11:44:38 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-04-05 11:05:29 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-04-06 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-04-07 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-04-08 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-04-09 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-04-10 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-04-11 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-04-12 00:00:01 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-04-13 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-04-14 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-04-15 00:00:01 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-04-16 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-04-17 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-04-18 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-04-19 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-04-20 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-04-21 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-04-22 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-04-23 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-04-24 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-04-25 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-04-28 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-05-01 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-05-04 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-05-07 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-05-10 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-05-13 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-05-16 00:00:02 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-05-19 00:00:01 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-05-22 00:00:02 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-05-25 00:00:03 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-05-28 00:00:03 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-05-31 00:00:02 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-06-01 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-06-04 00:00:03 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-08-13 10:28:42 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-08-16 00:00:01 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-08-19 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-08-22 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-08-25 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-08-28 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-08-31 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-09-01 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-09-04 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-09-07 00:00:02 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-09-10 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-09-13 00:00:02 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-09-16 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-09-19 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-09-22 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-09-25 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-09-28 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-10-01 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-10-04 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-10-07 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-10-10 00:00:00 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-10-14 07:20:23 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-10-16 00:01:44 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-10-19 07:29:40 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-10-22 00:01:58 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-10-25 00:01:51 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-10-28 00:01:41 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-10-31 00:01:50 real-estate-to-rent_real-estate-for-sale.parquet

,url,title,price,original_price,price_per_sqm,location,posted,ad_id,reference_number,views,lat,lng,sold,posted_dt,cat0,cat1,Property area,Pets,Type,Floor,Parking,Furnishing,Included,Online viewing,Air conditioning,Construction year,Energy Efficiency,Bedrooms,Bathrooms,images,description,Square meter price,Reference number,Plot area,Postal code,Minimum stay,Share,Density,Coverage,Land type,Plot Type,Parcel number,Planning zone,Registration block,Registration number,Condition,Area
905,https://www.bazaraki.com/adv/6065536_1-bedroom-apartment-to-rent/,1-bedroom apartment to rent,1200,NaN,NaN,"Limassol, Agios Tychon Tourist Area",29.10.2025 20:41,6065536,NaN,28,NaN,NaN,False,2025-10-29T20:41:00,Cyprus real estate to rent,"Apartments, flats to rent",60.00,Allowed,Apartment,1st,Uncovered,Fully Furnished,"Elevator, Balcony",Yes,"Full, all rooms",None,C,1,1,"[https://cdn1.bazaraki.com/media/cache1/27/20/2720ab69842dd575c7235e2b0ff2c885.webp, https://cdn...","1-Bedroom Apartment for Rent – Prime Tourist Area, Opposite Four Seasons Hotel\nThis fully furni...",None,None,NaN,NaN,None,None,None,None,None,None,None,None,NaN,NaN,None,NaN

Reading output/2025-11-01 00:02:19 real-estate-to-rent_real-estate-for-sale.parquet

,url,title,price,original_price,price_per_sqm,location,posted,ad_id,reference_number,views,lat,lng,sold,posted_dt,cat0,cat1,Reference number,Property area,Type,Online viewing,Energy Efficiency,Square meter price,images,description,Pets,Parking,Furnishing,Included,Air conditioning,Bedrooms,Bathrooms,Floor,Construction year,Plot area,Postal code,Minimum stay,Share,Density,Coverage,Land type,Plot Type,Parcel number,Planning zone,Registration block,Registration number,Condition,Area
859,https://www.bazaraki.com/adv/6065536_1-bedroom-apartment-to-rent/,1-bedroom apartment to rent,1200,NaN,NaN,"Limassol, Agios Tychon Tourist Area",29.10.2025 20:41,6065536,NaN,36,NaN,NaN,False,2025-10-29T20:41:00,Cyprus real estate to rent,"Apartments, flats to rent",None,60.00,Apartment,Yes,C,None,"[https://cdn1.bazaraki.com/media/cache1/27/20/2720ab69842dd575c7235e2b0ff2c885.webp, https://cdn...","1-Bedroom Apartment for Rent – Prime Tourist Area, Opposite Four Seasons Hotel\nThis fully furni...",Allowed,Uncovered,Fully Furnished,"Elevator, Balcony","Full, all rooms",1,1,1st,None,NaN,NaN,None,None,None,None,None,None,None,None,NaN,NaN,None,NaN

Reading output/2025-11-01 11:23:53 real-estate-to-rent_real-estate-for-sale.parquet

,url,title,price,original_price,price_per_sqm,location,posted,ad_id,reference_number,views,lat,lng,sold,posted_dt,cat0,cat1,Property area,Pets,Type,Parking,Plot area,Furnishing,Online viewing,Air conditioning,Construction year,Energy Efficiency,Bedrooms,Bathrooms,images,description,Reference number,Floor,Included,Square meter price,Postal code,Density,Coverage,Land type,Plot Type,Planning zone,Condition,Area,Share,Parcel number,Registration number,Registration block,Minimum stay
1642,https://www.bazaraki.com/adv/6065536_1-bedroom-apartment-to-rent/,1-bedroom apartment to rent,1200,NaN,NaN,"Limassol, Agios Tychon Tourist Area",29.10.2025 20:41,6065536,NaN,42,34.71,33.12,False,2025-10-29T20:41:00,Cyprus real estate to rent,"Apartments, flats to rent",60.00,Allowed,Apartment,Uncovered,NaN,Fully Furnished,Yes,"Full, all rooms",None,C,1,1,"[https://cdn1.bazaraki.com/media/cache1/27/20/2720ab69842dd575c7235e2b0ff2c885.webp, https://cdn...","1-Bedroom Apartment for Rent – Prime Tourist Area, Opposite Four Seasons Hotel\nThis fully furni...",None,1st,"Elevator, Balcony",None,NaN,None,None,None,None,None,None,NaN,None,None,NaN,NaN,None

Reading output/2025-11-04 00:01:41 real-estate-to-rent_real-estate-for-sale.parquet

,url,title,price,original_price,price_per_sqm,location,posted,ad_id,reference_number,views,lat,lng,sold,posted_dt,cat0,cat1,Reference number,Property area,Type,Parking,Condition,Furnishing,Air conditioning,Energy Efficiency,Bedrooms,Square meter price,Bathrooms,images,description,Share,Density,Coverage,Land type,Plot area,Plot Type,Planning zone,Online viewing,Included,Floor,Postal code,Construction year,Parcel number,Area,Registration block,Registration number,Pets,Minimum stay
12984,https://www.bazaraki.com/adv/6065536_1-bedroom-apartment-to-rent/,1-bedroom apartment to rent,1200,NaN,NaN,"Limassol, Agios Tychon Tourist Area",29.10.2025 20:41,6065536,NaN,62,34.71,33.12,False,2025-10-29T20:41:00,Cyprus real estate to rent,"Apartments, flats to rent",None,60.00,Apartment,Uncovered,None,Fully Furnished,"Full, all rooms",C,1,None,1,"[https://cdn1.bazaraki.com/media/cache1/27/20/2720ab69842dd575c7235e2b0ff2c885.webp, https://cdn...","1-Bedroom Apartment for Rent – Prime Tourist Area, Opposite Four Seasons Hotel\nThis fully furni...",None,None,None,None,NaN,None,None,Yes,"Elevator, Balcony",1st,NaN,None,None,NaN,NaN,NaN,Allowed,None

Reading output/2025-11-07 00:01:37 real-estate-to-rent_real-estate-for-sale.parquet

,url,title,price,original_price,price_per_sqm,location,posted,ad_id,reference_number,views,lat,lng,sold,posted_dt,cat0,cat1,Reference number,Property area,Type,Included,Construction year,Energy Efficiency,Square meter price,images,description,Parking,Furnishing,Online viewing,Air conditioning,Bedrooms,Pets,Floor,Bathrooms,Postal code,Plot area,Minimum stay,Area,Condition,Share,Density,Coverage,Land type,Plot Type,Parcel number,Planning zone,Registration block,Registration number
2643,https://www.bazaraki.com/adv/6065536_1-bedroom-apartment-to-rent/,1-bedroom apartment to rent,1200,NaN,NaN,"Limassol, Agios Tychon Tourist Area",29.10.2025 20:41,6065536,NaN,85,34.71,33.12,False,2025-10-29T20:41:00,Cyprus real estate to rent,"Apartments, flats to rent",None,60.00,Apartment,"Elevator, Balcony",None,C,None,"[https://cdn1.bazaraki.com/media/cache1/27/20/2720ab69842dd575c7235e2b0ff2c885.webp, https://cdn...","1-Bedroom Apartment for Rent – Prime Tourist Area, Opposite Four Seasons Hotel\nThis fully furni...",Uncovered,Fully Furnished,Yes,"Full, all rooms",1,Allowed,1st,1,NaN,NaN,None,NaN,None,None,None,None,None,None,None,None,NaN,NaN

Reading output/2025-11-10 00:01:32 real-estate-to-rent_real-estate-for-sale.parquet

,url,title,price,original_price,price_per_sqm,location,posted,ad_id,reference_number,views,lat,lng,sold,posted_dt,cat0,cat1,Pets,Postal code,Online viewing,images,description,Reference number,Property area,Type,Floor,Parking,Furnishing,Air conditioning,Construction year,Energy Efficiency,Bedrooms,Bathrooms,Included,Plot area,Square meter price,Minimum stay,Area,Condition,Share,Land type,Plot Type,Density,Coverage,Parcel number,Planning zone,Registration number,Registration block
3705,https://www.bazaraki.com/adv/6065536_1-bedroom-apartment-to-rent/,1-bedroom apartment to rent,1200,NaN,NaN,"Limassol, Agios Tychon Tourist Area",29.10.2025 20:41,6065536,NaN,101,34.71,33.12,False,2025-10-29T20:41:00,Cyprus real estate to rent,"Apartments, flats to rent",Allowed,NaN,Yes,"[https://cdn1.bazaraki.com/media/cache1/27/20/2720ab69842dd575c7235e2b0ff2c885.webp, https://cdn...","1-Bedroom Apartment for Rent – Prime Tourist Area, Opposite Four Seasons Hotel\nThis fully furni...",None,60.00,Apartment,1st,Uncovered,Fully Furnished,"Full, all rooms",None,C,1,1,"Elevator, Balcony",NaN,None,None,NaN,None,None,None,None,None,None,None,None,NaN,NaN

Reading output/2025-11-13 00:01:28 real-estate-to-rent_real-estate-for-sale.parquet

,url,title,price,original_price,price_per_sqm,location,posted,ad_id,reference_number,views,lat,lng,sold,posted_dt,cat0,cat1,Reference number,Property area,Type,Floor,Parking,Furnishing,Included,Online viewing,Air conditioning,Construction year,Energy Efficiency,Bedrooms,Bathrooms,images,description,Postal code,Share,Land type,Plot area,Plot Type,Planning zone,Pets,Square meter price,Minimum stay,Area,Condition,Density,Coverage,Parcel number,Registration block,Registration number
4536,https://www.bazaraki.com/adv/6065536_1-bedroom-apartment-to-rent/,1-bedroom apartment to rent,1200,NaN,NaN,"Limassol, Agios Tychon Tourist Area",29.10.2025 20:41,6065536,NaN,125,34.71,33.12,False,2025-10-29T20:41:00,Cyprus real estate to rent,"Apartments, flats to rent",None,60.00,Apartment,1st,Uncovered,Fully Furnished,"Elevator, Balcony",Yes,"Full, all rooms",None,C,1,1,"[https://cdn1.bazaraki.com/media/cache1/27/20/2720ab69842dd575c7235e2b0ff2c885.webp, https://cdn...","1-Bedroom Apartment for Rent – Prime Tourist Area, Opposite Four Seasons Hotel\nThis fully furni...",NaN,None,None,NaN,None,None,Allowed,None,None,NaN,None,None,None,None,NaN,NaN

Reading output/2025-11-19 00:01:35 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-11-22 00:01:24 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-11-25 00:04:21 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-11-28 00:01:35 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-12-01 00:01:33 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-12-04 00:01:37 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-12-07 00:01:32 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-12-10 00:01:36 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-12-13 00:01:24 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-12-16 00:01:40 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-12-19 00:01:32 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-12-22 00:01:27 real-estate-to-rent_real-estate-for-sale.parquet
Reading output/2025-12-25 00:01:24 real-estate-to-rent_real-estate-for-sale.parquet